# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_medequivalence', [dirname(__file__)])
        except ImportError:
            import _medequivalence
            return _medequivalence
        if fp is not None:
            try:
                _mod = imp.load_module('_medequivalence', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _medequivalence = swig_import_helper()
    del swig_import_helper
else:
    import _medequivalence
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator_medequivalence_module(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator_medequivalence_module, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator_medequivalence_module, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _medequivalence.delete_SwigPyIterator_medequivalence_module
    __del__ = lambda self : None;
    def value(self): return _medequivalence.SwigPyIterator_medequivalence_module_value(self)
    def incr(self, n=1): return _medequivalence.SwigPyIterator_medequivalence_module_incr(self, n)
    def decr(self, n=1): return _medequivalence.SwigPyIterator_medequivalence_module_decr(self, n)
    def distance(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module_distance(self, *args)
    def equal(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module_equal(self, *args)
    def copy(self): return _medequivalence.SwigPyIterator_medequivalence_module_copy(self)
    def next(self): return _medequivalence.SwigPyIterator_medequivalence_module_next(self)
    def __next__(self): return _medequivalence.SwigPyIterator_medequivalence_module___next__(self)
    def previous(self): return _medequivalence.SwigPyIterator_medequivalence_module_previous(self)
    def advance(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module_advance(self, *args)
    def __eq__(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module___eq__(self, *args)
    def __ne__(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module___ne__(self, *args)
    def __iadd__(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module___iadd__(self, *args)
    def __isub__(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module___isub__(self, *args)
    def __add__(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module___add__(self, *args)
    def __sub__(self, *args): return _medequivalence.SwigPyIterator_medequivalence_module___sub__(self, *args)
    def __iter__(self): return self
    def __iter__(self): return self
SwigPyIterator_medequivalence_module_swigregister = _medequivalence.SwigPyIterator_medequivalence_module_swigregister
SwigPyIterator_medequivalence_module_swigregister(SwigPyIterator_medequivalence_module)

ABSOLUTE_H5IPUBLIC_H = _medequivalence.ABSOLUTE_H5IPUBLIC_H
ABSOLUTE_H5PUBLIC_H = _medequivalence.ABSOLUTE_H5PUBLIC_H
HAVE_CC_C99 = _medequivalence.HAVE_CC_C99
HAVE_CUSERID = _medequivalence.HAVE_CUSERID
HAVE_DLFCN_H = _medequivalence.HAVE_DLFCN_H
HAVE_FTIME = _medequivalence.HAVE_FTIME
HAVE_GETEUID = _medequivalence.HAVE_GETEUID
HAVE_GETPWUID = _medequivalence.HAVE_GETPWUID
HAVE_GETTIMEOFDAY = _medequivalence.HAVE_GETTIMEOFDAY
HAVE_H5IPUBLIC_H = _medequivalence.HAVE_H5IPUBLIC_H
HAVE_H5PUBLIC_H = _medequivalence.HAVE_H5PUBLIC_H
HAVE_INTTYPES_H = _medequivalence.HAVE_INTTYPES_H
HAVE_LIBHDF5 = _medequivalence.HAVE_LIBHDF5
HAVE_MALLOC_H = _medequivalence.HAVE_MALLOC_H
HAVE_MEMORY_H = _medequivalence.HAVE_MEMORY_H
HAVE_PWD_H = _medequivalence.HAVE_PWD_H
HAVE_PYTHON = _medequivalence.HAVE_PYTHON
HAVE_STDBOOL_H = _medequivalence.HAVE_STDBOOL_H
HAVE_STDINT_H = _medequivalence.HAVE_STDINT_H
HAVE_STDLIB_H = _medequivalence.HAVE_STDLIB_H
HAVE_STRINGS_H = _medequivalence.HAVE_STRINGS_H
HAVE_STRING_H = _medequivalence.HAVE_STRING_H
HAVE_SYS_STAT_H = _medequivalence.HAVE_SYS_STAT_H
HAVE_SYS_TIMEB_H = _medequivalence.HAVE_SYS_TIMEB_H
HAVE_SYS_TIME_H = _medequivalence.HAVE_SYS_TIME_H
HAVE_SYS_TYPES_H = _medequivalence.HAVE_SYS_TYPES_H
HAVE_UNISTD_H = _medequivalence.HAVE_UNISTD_H
HAVE__BOOL = _medequivalence.HAVE__BOOL
LT_OBJDIR = _medequivalence.LT_OBJDIR
MED_API_23 = _medequivalence.MED_API_23
MED_CHECK_23FORMAT = _medequivalence.MED_CHECK_23FORMAT
MED_HAVE_FORTRAN = _medequivalence.MED_HAVE_FORTRAN
MED_HAVE_PYTHON = _medequivalence.MED_HAVE_PYTHON
MESGERR = _medequivalence.MESGERR
PACKAGE = _medequivalence.PACKAGE
PACKAGE_BUGREPORT = _medequivalence.PACKAGE_BUGREPORT
PACKAGE_NAME = _medequivalence.PACKAGE_NAME
PACKAGE_STRING = _medequivalence.PACKAGE_STRING
PACKAGE_TARNAME = _medequivalence.PACKAGE_TARNAME
PACKAGE_URL = _medequivalence.PACKAGE_URL
PACKAGE_VERSION = _medequivalence.PACKAGE_VERSION
SIZEOF_FORTRAN_INTEGER = _medequivalence.SIZEOF_FORTRAN_INTEGER
SIZEOF_INT = _medequivalence.SIZEOF_INT
SIZEOF_LONG = _medequivalence.SIZEOF_LONG
STDC_HEADERS = _medequivalence.STDC_HEADERS
TIME_WITH_SYS_TIME = _medequivalence.TIME_WITH_SYS_TIME
VERSION = _medequivalence.VERSION
H5F_LIBVER_18 = _medequivalence.H5F_LIBVER_18
MED_MAJOR_NUM = _medequivalence.MED_MAJOR_NUM
MED_MINOR_NUM = _medequivalence.MED_MINOR_NUM
MED_RELEASE_NUM = _medequivalence.MED_RELEASE_NUM
MED_NUM_MAJEUR = _medequivalence.MED_NUM_MAJEUR
MED_NUM_MINEUR = _medequivalence.MED_NUM_MINEUR
MED_NUM_RELEASE = _medequivalence.MED_NUM_RELEASE
MED_VERSION_STR = _medequivalence.MED_VERSION_STR
MED_MAX_PARA = _medequivalence.MED_MAX_PARA
MED_COMMENT_SIZE = _medequivalence.MED_COMMENT_SIZE
MED_IDENT_SIZE = _medequivalence.MED_IDENT_SIZE
MED_NAME_SIZE = _medequivalence.MED_NAME_SIZE
MED_SNAME_SIZE = _medequivalence.MED_SNAME_SIZE
MED_LNAME_SIZE = _medequivalence.MED_LNAME_SIZE
MED_SNAME_BLANK = _medequivalence.MED_SNAME_BLANK
MED_NAME_BLANK = _medequivalence.MED_NAME_BLANK
MED_PATHNAME_SIZE = _medequivalence.MED_PATHNAME_SIZE
MED_MAX_CHFID_PATH = _medequivalence.MED_MAX_CHFID_PATH
MED_FULL_INTERLACE = _medequivalence.MED_FULL_INTERLACE
MED_NO_INTERLACE = _medequivalence.MED_NO_INTERLACE
MED_UNDEF_INTERLACE = _medequivalence.MED_UNDEF_INTERLACE
MED_UNDEF_STMODE = _medequivalence.MED_UNDEF_STMODE
MED_GLOBAL_STMODE = _medequivalence.MED_GLOBAL_STMODE
MED_COMPACT_STMODE = _medequivalence.MED_COMPACT_STMODE
MED_GLOBAL_PFLMODE = _medequivalence.MED_GLOBAL_PFLMODE
MED_COMPACT_PFLMODE = _medequivalence.MED_COMPACT_PFLMODE
MED_UNDEF_PFLMODE = _medequivalence.MED_UNDEF_PFLMODE
MED_ACC_RDONLY = _medequivalence.MED_ACC_RDONLY
MED_ACC_RDWR = _medequivalence.MED_ACC_RDWR
MED_ACC_RDEXT = _medequivalence.MED_ACC_RDEXT
MED_ACC_CREAT = _medequivalence.MED_ACC_CREAT
MED_ACC_UNDEF = _medequivalence.MED_ACC_UNDEF
MED_UNSTRUCTURED_MESH = _medequivalence.MED_UNSTRUCTURED_MESH
MED_STRUCTURED_MESH = _medequivalence.MED_STRUCTURED_MESH
MED_UNDEF_MESH_TYPE = _medequivalence.MED_UNDEF_MESH_TYPE
MED_CARTESIAN_GRID = _medequivalence.MED_CARTESIAN_GRID
MED_POLAR_GRID = _medequivalence.MED_POLAR_GRID
MED_CURVILINEAR_GRID = _medequivalence.MED_CURVILINEAR_GRID
MED_UNDEF_GRID_TYPE = _medequivalence.MED_UNDEF_GRID_TYPE
MED_CELL = _medequivalence.MED_CELL
MED_DESCENDING_FACE = _medequivalence.MED_DESCENDING_FACE
MED_DESCENDING_EDGE = _medequivalence.MED_DESCENDING_EDGE
MED_NODE = _medequivalence.MED_NODE
MED_NODE_ELEMENT = _medequivalence.MED_NODE_ELEMENT
MED_STRUCT_ELEMENT = _medequivalence.MED_STRUCT_ELEMENT
MED_ALL_ENTITY_TYPE = _medequivalence.MED_ALL_ENTITY_TYPE
MED_UNDEF_ENTITY_TYPE = _medequivalence.MED_UNDEF_ENTITY_TYPE
MED_N_ENTITY_TYPES = _medequivalence.MED_N_ENTITY_TYPES
MED_COORDINATE = _medequivalence.MED_COORDINATE
MED_CONNECTIVITY = _medequivalence.MED_CONNECTIVITY
MED_NAME = _medequivalence.MED_NAME
MED_NUMBER = _medequivalence.MED_NUMBER
MED_FAMILY_NUMBER = _medequivalence.MED_FAMILY_NUMBER
MED_COORDINATE_AXIS1 = _medequivalence.MED_COORDINATE_AXIS1
MED_COORDINATE_AXIS2 = _medequivalence.MED_COORDINATE_AXIS2
MED_COORDINATE_AXIS3 = _medequivalence.MED_COORDINATE_AXIS3
MED_INDEX_FACE = _medequivalence.MED_INDEX_FACE
MED_INDEX_NODE = _medequivalence.MED_INDEX_NODE
MED_GLOBAL_NUMBER = _medequivalence.MED_GLOBAL_NUMBER
MED_VARIABLE_ATTRIBUTE = _medequivalence.MED_VARIABLE_ATTRIBUTE
MED_COORDINATE_TRSF = _medequivalence.MED_COORDINATE_TRSF
MED_UNDEF_DATATYPE = _medequivalence.MED_UNDEF_DATATYPE
MED_INTERNAL_FLOAT64 = _medequivalence.MED_INTERNAL_FLOAT64
MED_INTERNAL_INT32 = _medequivalence.MED_INTERNAL_INT32
MED_INTERNAL_INT64 = _medequivalence.MED_INTERNAL_INT64
MED_INTERNAL_INT = _medequivalence.MED_INTERNAL_INT
MED_INTERNAL_NAME = _medequivalence.MED_INTERNAL_NAME
MED_INTERNAL_SNAME = _medequivalence.MED_INTERNAL_SNAME
MED_INTERNAL_LNAME = _medequivalence.MED_INTERNAL_LNAME
MED_INTERNAL_IDENT = _medequivalence.MED_INTERNAL_IDENT
MED_INTERNAL_CHAR = _medequivalence.MED_INTERNAL_CHAR
MED_INTERNAL_UNDEF = _medequivalence.MED_INTERNAL_UNDEF
MED_FLOAT64 = _medequivalence.MED_FLOAT64
MED_INT32 = _medequivalence.MED_INT32
MED_INT64 = _medequivalence.MED_INT64
MED_INT = _medequivalence.MED_INT
MED_ATT_FLOAT64 = _medequivalence.MED_ATT_FLOAT64
MED_ATT_INT = _medequivalence.MED_ATT_INT
MED_ATT_NAME = _medequivalence.MED_ATT_NAME
MED_ATT_UNDEF = _medequivalence.MED_ATT_UNDEF
MED_MESH = _medequivalence.MED_MESH
MED_FIELD = _medequivalence.MED_FIELD
MED_LIBRARY = _medequivalence.MED_LIBRARY
MED_FILE = _medequivalence.MED_FILE
MED_MESH_SUPPORT = _medequivalence.MED_MESH_SUPPORT
MED_ELSTRUCT = _medequivalence.MED_ELSTRUCT
MED_FAMILY = _medequivalence.MED_FAMILY
MED_EQUIVALENCE = _medequivalence.MED_EQUIVALENCE
MED_GROUP = _medequivalence.MED_GROUP
MED_JOINT = _medequivalence.MED_JOINT
MED_LOCALIZATION = _medequivalence.MED_LOCALIZATION
MED_PROFILE = _medequivalence.MED_PROFILE
MED_FILTER = _medequivalence.MED_FILTER
MED_INTERPOLATION = _medequivalence.MED_INTERPOLATION
MED_NUMERICAL_DATA = _medequivalence.MED_NUMERICAL_DATA
MED_LINK = _medequivalence.MED_LINK
MED_CLASS_UNDEF = _medequivalence.MED_CLASS_UNDEF
MED_CLASS_ALL = _medequivalence.MED_CLASS_ALL
MED_POINT1 = _medequivalence.MED_POINT1
MED_SEG2 = _medequivalence.MED_SEG2
MED_SEG3 = _medequivalence.MED_SEG3
MED_SEG4 = _medequivalence.MED_SEG4
MED_TRIA3 = _medequivalence.MED_TRIA3
MED_QUAD4 = _medequivalence.MED_QUAD4
MED_TRIA6 = _medequivalence.MED_TRIA6
MED_TRIA7 = _medequivalence.MED_TRIA7
MED_QUAD8 = _medequivalence.MED_QUAD8
MED_QUAD9 = _medequivalence.MED_QUAD9
MED_TETRA4 = _medequivalence.MED_TETRA4
MED_PYRA5 = _medequivalence.MED_PYRA5
MED_PENTA6 = _medequivalence.MED_PENTA6
MED_HEXA8 = _medequivalence.MED_HEXA8
MED_TETRA10 = _medequivalence.MED_TETRA10
MED_OCTA12 = _medequivalence.MED_OCTA12
MED_PYRA13 = _medequivalence.MED_PYRA13
MED_PENTA15 = _medequivalence.MED_PENTA15
MED_HEXA20 = _medequivalence.MED_HEXA20
MED_HEXA27 = _medequivalence.MED_HEXA27
MED_POLYGON = _medequivalence.MED_POLYGON
MED_POLYGON2 = _medequivalence.MED_POLYGON2
MED_POLYHEDRON = _medequivalence.MED_POLYHEDRON
MED_STRUCT_GEO_INTERNAL = _medequivalence.MED_STRUCT_GEO_INTERNAL
MED_STRUCT_GEO_SUP_INTERNAL = _medequivalence.MED_STRUCT_GEO_SUP_INTERNAL
MED_NONE = _medequivalence.MED_NONE
MED_NO_GEOTYPE = _medequivalence.MED_NO_GEOTYPE
MED_UNDEF_GEOTYPE = _medequivalence.MED_UNDEF_GEOTYPE
MED_UNDEF_GEOMETRY_TYPE = _medequivalence.MED_UNDEF_GEOMETRY_TYPE
MED_ALL_GEOTYPE = _medequivalence.MED_ALL_GEOTYPE
MED_GEO_ALL = _medequivalence.MED_GEO_ALL
MED_N_CELL_GEO = _medequivalence.MED_N_CELL_GEO
MED_N_CELL_FIXED_GEO = _medequivalence.MED_N_CELL_FIXED_GEO
MED_N_CELL_GEO_FIXED_CON = _medequivalence.MED_N_CELL_GEO_FIXED_CON
MED_N_FACE_GEO = _medequivalence.MED_N_FACE_GEO
MED_N_FACE_FIXED_GEO = _medequivalence.MED_N_FACE_FIXED_GEO
MED_N_FACE_GEO_FIXED_CON = _medequivalence.MED_N_FACE_GEO_FIXED_CON
MED_N_EDGE_TYPES = _medequivalence.MED_N_EDGE_TYPES
MED_N_EDGE_FIXED_GEO = _medequivalence.MED_N_EDGE_FIXED_GEO
MED_N_EDGE_GEO_FIXED_CON = _medequivalence.MED_N_EDGE_GEO_FIXED_CON
MED_N_NODE_GEO = _medequivalence.MED_N_NODE_GEO
MED_N_NODE_FIXED_GEO = _medequivalence.MED_N_NODE_FIXED_GEO
MED_N_NODE_GEO_FIXED_CON = _medequivalence.MED_N_NODE_GEO_FIXED_CON
MED_NODAL = _medequivalence.MED_NODAL
MED_DESCENDING = _medequivalence.MED_DESCENDING
MED_UNDEF_CONNECTIVITY_MODE = _medequivalence.MED_UNDEF_CONNECTIVITY_MODE
MED_NO_CMODE = _medequivalence.MED_NO_CMODE
MED_CARTESIAN = _medequivalence.MED_CARTESIAN
MED_CYLINDRICAL = _medequivalence.MED_CYLINDRICAL
MED_SPHERICAL = _medequivalence.MED_SPHERICAL
MED_UNDEF_AXIS_TYPE = _medequivalence.MED_UNDEF_AXIS_TYPE
MED_FALSE = _medequivalence.MED_FALSE
MED_TRUE = _medequivalence.MED_TRUE
MED_GAUSS_ELNO = _medequivalence.MED_GAUSS_ELNO
MED_IPOINT_ELNO = _medequivalence.MED_IPOINT_ELNO
MED_NO_NAME = _medequivalence.MED_NO_NAME
MED_NO_MESHNAME = _medequivalence.MED_NO_MESHNAME
MED_NO_MESH = _medequivalence.MED_NO_MESH
MED_NO_MESH_SUPPORT = _medequivalence.MED_NO_MESH_SUPPORT
MED_NO_LOCALIZATION = _medequivalence.MED_NO_LOCALIZATION
MED_NO_INTERPOLATION = _medequivalence.MED_NO_INTERPOLATION
MED_NO_IPOINT_INTERNAL = _medequivalence.MED_NO_IPOINT_INTERNAL
MED_NO_PROFILE = _medequivalence.MED_NO_PROFILE
MED_NO_GROUP = _medequivalence.MED_NO_GROUP
MED_ALLENTITIES_PROFILE = _medequivalence.MED_ALLENTITIES_PROFILE
MED_NO_PROFILE_INTERNAL = _medequivalence.MED_NO_PROFILE_INTERNAL
MED_SAME_PROFILE_INTERNAL = _medequivalence.MED_SAME_PROFILE_INTERNAL
MED_ALL_CONSTITUENT = _medequivalence.MED_ALL_CONSTITUENT
MED_UNDEF_SIZE = _medequivalence.MED_UNDEF_SIZE
MED_NO_PROFILE_SIZE = _medequivalence.MED_NO_PROFILE_SIZE
MED_SORT_DTIT = _medequivalence.MED_SORT_DTIT
MED_SORT_ITDT = _medequivalence.MED_SORT_ITDT
MED_SORT_UNDEF = _medequivalence.MED_SORT_UNDEF
MED_NO_DT = _medequivalence.MED_NO_DT
MED_NO_IT = _medequivalence.MED_NO_IT
MED_UNDEF_DT = _medequivalence.MED_UNDEF_DT
MED_ATT_NOT_FILLED = _medequivalence.MED_ATT_NOT_FILLED
MED_MAX_FILTER_SPACES = _medequivalence.MED_MAX_FILTER_SPACES
class med_filter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_filter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_filter, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nspaces"] = _medequivalence.med_filter_nspaces_set
    __swig_getmethods__["nspaces"] = _medequivalence.med_filter_nspaces_get
    if _newclass:nspaces = _swig_property(_medequivalence.med_filter_nspaces_get, _medequivalence.med_filter_nspaces_set)
    __swig_setmethods__["memspace"] = _medequivalence.med_filter_memspace_set
    __swig_getmethods__["memspace"] = _medequivalence.med_filter_memspace_get
    if _newclass:memspace = _swig_property(_medequivalence.med_filter_memspace_get, _medequivalence.med_filter_memspace_set)
    __swig_setmethods__["diskspace"] = _medequivalence.med_filter_diskspace_set
    __swig_getmethods__["diskspace"] = _medequivalence.med_filter_diskspace_get
    if _newclass:diskspace = _swig_property(_medequivalence.med_filter_diskspace_get, _medequivalence.med_filter_diskspace_set)
    __swig_setmethods__["nentity"] = _medequivalence.med_filter_nentity_set
    __swig_getmethods__["nentity"] = _medequivalence.med_filter_nentity_get
    if _newclass:nentity = _swig_property(_medequivalence.med_filter_nentity_get, _medequivalence.med_filter_nentity_set)
    __swig_setmethods__["nvaluesperentity"] = _medequivalence.med_filter_nvaluesperentity_set
    __swig_getmethods__["nvaluesperentity"] = _medequivalence.med_filter_nvaluesperentity_get
    if _newclass:nvaluesperentity = _swig_property(_medequivalence.med_filter_nvaluesperentity_get, _medequivalence.med_filter_nvaluesperentity_set)
    __swig_setmethods__["nconstituentpervalue"] = _medequivalence.med_filter_nconstituentpervalue_set
    __swig_getmethods__["nconstituentpervalue"] = _medequivalence.med_filter_nconstituentpervalue_get
    if _newclass:nconstituentpervalue = _swig_property(_medequivalence.med_filter_nconstituentpervalue_get, _medequivalence.med_filter_nconstituentpervalue_set)
    __swig_setmethods__["constituentselect"] = _medequivalence.med_filter_constituentselect_set
    __swig_getmethods__["constituentselect"] = _medequivalence.med_filter_constituentselect_get
    if _newclass:constituentselect = _swig_property(_medequivalence.med_filter_constituentselect_get, _medequivalence.med_filter_constituentselect_set)
    __swig_setmethods__["switchmode"] = _medequivalence.med_filter_switchmode_set
    __swig_getmethods__["switchmode"] = _medequivalence.med_filter_switchmode_get
    if _newclass:switchmode = _swig_property(_medequivalence.med_filter_switchmode_get, _medequivalence.med_filter_switchmode_set)
    __swig_setmethods__["filterarraysize"] = _medequivalence.med_filter_filterarraysize_set
    __swig_getmethods__["filterarraysize"] = _medequivalence.med_filter_filterarraysize_get
    if _newclass:filterarraysize = _swig_property(_medequivalence.med_filter_filterarraysize_get, _medequivalence.med_filter_filterarraysize_set)
    __swig_setmethods__["filterarray23v30"] = _medequivalence.med_filter_filterarray23v30_set
    __swig_getmethods__["filterarray23v30"] = _medequivalence.med_filter_filterarray23v30_get
    if _newclass:filterarray23v30 = _swig_property(_medequivalence.med_filter_filterarray23v30_get, _medequivalence.med_filter_filterarray23v30_set)
    __swig_setmethods__["profilearraysize"] = _medequivalence.med_filter_profilearraysize_set
    __swig_getmethods__["profilearraysize"] = _medequivalence.med_filter_profilearraysize_get
    if _newclass:profilearraysize = _swig_property(_medequivalence.med_filter_profilearraysize_get, _medequivalence.med_filter_profilearraysize_set)
    __swig_setmethods__["storagemode"] = _medequivalence.med_filter_storagemode_set
    __swig_getmethods__["storagemode"] = _medequivalence.med_filter_storagemode_get
    if _newclass:storagemode = _swig_property(_medequivalence.med_filter_storagemode_get, _medequivalence.med_filter_storagemode_set)
    __swig_setmethods__["profilename"] = _medequivalence.med_filter_profilename_set
    __swig_getmethods__["profilename"] = _medequivalence.med_filter_profilename_get
    if _newclass:profilename = _swig_property(_medequivalence.med_filter_profilename_get, _medequivalence.med_filter_profilename_set)
    def __init__(self): 
        """__init__(self) -> med_filter"""
        this = _medequivalence.new_med_filter()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _medequivalence.delete_med_filter
    __del__ = lambda self : None;
med_filter_swigregister = _medequivalence.med_filter_swigregister
med_filter_swigregister(med_filter)

MED_NO_FILTER_SIZE = _medequivalence.MED_NO_FILTER_SIZE
MED_NO_PROFILE_F = _medequivalence.MED_NO_PROFILE_F
class med_file_version(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_file_version, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_file_version, name)
    __repr__ = _swig_repr
    __swig_setmethods__["majeur"] = _medequivalence.med_file_version_majeur_set
    __swig_getmethods__["majeur"] = _medequivalence.med_file_version_majeur_get
    if _newclass:majeur = _swig_property(_medequivalence.med_file_version_majeur_get, _medequivalence.med_file_version_majeur_set)
    __swig_setmethods__["mineur"] = _medequivalence.med_file_version_mineur_set
    __swig_getmethods__["mineur"] = _medequivalence.med_file_version_mineur_get
    if _newclass:mineur = _swig_property(_medequivalence.med_file_version_mineur_get, _medequivalence.med_file_version_mineur_set)
    __swig_setmethods__["release"] = _medequivalence.med_file_version_release_set
    __swig_getmethods__["release"] = _medequivalence.med_file_version_release_get
    if _newclass:release = _swig_property(_medequivalence.med_file_version_release_get, _medequivalence.med_file_version_release_set)
    def __init__(self): 
        """__init__(self) -> med_file_version"""
        this = _medequivalence.new_med_file_version()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _medequivalence.delete_med_file_version
    __del__ = lambda self : None;
med_file_version_swigregister = _medequivalence.med_file_version_swigregister
med_file_version_swigregister(med_file_version)

class med_memfile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_memfile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_memfile, name)
    __repr__ = _swig_repr
    __swig_setmethods__["app_image_ptr"] = _medequivalence.med_memfile_app_image_ptr_set
    __swig_getmethods__["app_image_ptr"] = _medequivalence.med_memfile_app_image_ptr_get
    if _newclass:app_image_ptr = _swig_property(_medequivalence.med_memfile_app_image_ptr_get, _medequivalence.med_memfile_app_image_ptr_set)
    __swig_setmethods__["app_image_size"] = _medequivalence.med_memfile_app_image_size_set
    __swig_getmethods__["app_image_size"] = _medequivalence.med_memfile_app_image_size_get
    if _newclass:app_image_size = _swig_property(_medequivalence.med_memfile_app_image_size_get, _medequivalence.med_memfile_app_image_size_set)
    __swig_setmethods__["ref_count"] = _medequivalence.med_memfile_ref_count_set
    __swig_getmethods__["ref_count"] = _medequivalence.med_memfile_ref_count_get
    if _newclass:ref_count = _swig_property(_medequivalence.med_memfile_ref_count_get, _medequivalence.med_memfile_ref_count_set)
    __swig_setmethods__["fapl_image_ptr"] = _medequivalence.med_memfile_fapl_image_ptr_set
    __swig_getmethods__["fapl_image_ptr"] = _medequivalence.med_memfile_fapl_image_ptr_get
    if _newclass:fapl_image_ptr = _swig_property(_medequivalence.med_memfile_fapl_image_ptr_get, _medequivalence.med_memfile_fapl_image_ptr_set)
    __swig_setmethods__["fapl_image_size"] = _medequivalence.med_memfile_fapl_image_size_set
    __swig_getmethods__["fapl_image_size"] = _medequivalence.med_memfile_fapl_image_size_get
    if _newclass:fapl_image_size = _swig_property(_medequivalence.med_memfile_fapl_image_size_get, _medequivalence.med_memfile_fapl_image_size_set)
    __swig_setmethods__["fapl_ref_count"] = _medequivalence.med_memfile_fapl_ref_count_set
    __swig_getmethods__["fapl_ref_count"] = _medequivalence.med_memfile_fapl_ref_count_get
    if _newclass:fapl_ref_count = _swig_property(_medequivalence.med_memfile_fapl_ref_count_get, _medequivalence.med_memfile_fapl_ref_count_set)
    __swig_setmethods__["vfd_image_ptr"] = _medequivalence.med_memfile_vfd_image_ptr_set
    __swig_getmethods__["vfd_image_ptr"] = _medequivalence.med_memfile_vfd_image_ptr_get
    if _newclass:vfd_image_ptr = _swig_property(_medequivalence.med_memfile_vfd_image_ptr_get, _medequivalence.med_memfile_vfd_image_ptr_set)
    __swig_setmethods__["vfd_image_size"] = _medequivalence.med_memfile_vfd_image_size_set
    __swig_getmethods__["vfd_image_size"] = _medequivalence.med_memfile_vfd_image_size_get
    if _newclass:vfd_image_size = _swig_property(_medequivalence.med_memfile_vfd_image_size_get, _medequivalence.med_memfile_vfd_image_size_set)
    __swig_setmethods__["vfd_ref_count"] = _medequivalence.med_memfile_vfd_ref_count_set
    __swig_getmethods__["vfd_ref_count"] = _medequivalence.med_memfile_vfd_ref_count_get
    if _newclass:vfd_ref_count = _swig_property(_medequivalence.med_memfile_vfd_ref_count_get, _medequivalence.med_memfile_vfd_ref_count_set)
    __swig_setmethods__["flags"] = _medequivalence.med_memfile_flags_set
    __swig_getmethods__["flags"] = _medequivalence.med_memfile_flags_get
    if _newclass:flags = _swig_property(_medequivalence.med_memfile_flags_get, _medequivalence.med_memfile_flags_set)
    def __init__(self): 
        """__init__(self) -> med_memfile"""
        this = _medequivalence.new_med_memfile()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _medequivalence.delete_med_memfile
    __del__ = lambda self : None;
med_memfile_swigregister = _medequivalence.med_memfile_swigregister
med_memfile_swigregister(med_memfile)

MED_PARTICLE_NAME = _medequivalence.MED_PARTICLE_NAME
MED_BALL_NAME = _medequivalence.MED_BALL_NAME
MED_BEAM_NAME = _medequivalence.MED_BEAM_NAME
MED_PARTICLE_LABEL = _medequivalence.MED_PARTICLE_LABEL
MED_BALL_DIAMETER = _medequivalence.MED_BALL_DIAMETER
MED_BEAM_THICKNESS = _medequivalence.MED_BEAM_THICKNESS
import medenum
class MEDBOOL(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDBOOL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDBOOL, name)
    __repr__ = _swig_repr
    def iterator(self): return _medequivalence.MEDBOOL_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medequivalence.MEDBOOL___nonzero__(self)
    def __bool__(self): return _medequivalence.MEDBOOL___bool__(self)
    def __len__(self): return _medequivalence.MEDBOOL___len__(self)
    def pop(self): return _medequivalence.MEDBOOL_pop(self)
    def __getslice__(self, *args): return _medequivalence.MEDBOOL___getslice__(self, *args)
    def __setslice__(self, *args): return _medequivalence.MEDBOOL___setslice__(self, *args)
    def __delslice__(self, *args): return _medequivalence.MEDBOOL___delslice__(self, *args)
    def __delitem__(self, *args): return _medequivalence.MEDBOOL___delitem__(self, *args)
    def __getitem__(self, *args): return _medequivalence.MEDBOOL___getitem__(self, *args)
    def __setitem__(self, *args): return _medequivalence.MEDBOOL___setitem__(self, *args)
    def append(self, *args): return _medequivalence.MEDBOOL_append(self, *args)
    def empty(self): return _medequivalence.MEDBOOL_empty(self)
    def size(self): return _medequivalence.MEDBOOL_size(self)
    def clear(self): return _medequivalence.MEDBOOL_clear(self)
    def swap(self, *args): return _medequivalence.MEDBOOL_swap(self, *args)
    def get_allocator(self): return _medequivalence.MEDBOOL_get_allocator(self)
    def begin(self): return _medequivalence.MEDBOOL_begin(self)
    def end(self): return _medequivalence.MEDBOOL_end(self)
    def rbegin(self): return _medequivalence.MEDBOOL_rbegin(self)
    def rend(self): return _medequivalence.MEDBOOL_rend(self)
    def pop_back(self): return _medequivalence.MEDBOOL_pop_back(self)
    def erase(self, *args): return _medequivalence.MEDBOOL_erase(self, *args)
    def __init__(self, *args): 
        this = _medequivalence.new_MEDBOOL(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medequivalence.MEDBOOL_push_back(self, *args)
    def front(self): return _medequivalence.MEDBOOL_front(self)
    def back(self): return _medequivalence.MEDBOOL_back(self)
    def assign(self, *args): return _medequivalence.MEDBOOL_assign(self, *args)
    def resize(self, *args): return _medequivalence.MEDBOOL_resize(self, *args)
    def insert(self, *args): return _medequivalence.MEDBOOL_insert(self, *args)
    def reserve(self, *args): return _medequivalence.MEDBOOL_reserve(self, *args)
    def capacity(self): return _medequivalence.MEDBOOL_capacity(self)
    __swig_destroy__ = _medequivalence.delete_MEDBOOL
    __del__ = lambda self : None;
MEDBOOL_swigregister = _medequivalence.MEDBOOL_swigregister
MEDBOOL_swigregister(MEDBOOL)
cvar = _medequivalence.cvar
MED_GET_ENTITY_TYPENAME = cvar.MED_GET_ENTITY_TYPENAME
MED_GET_CELL_GEOMETRY_TYPENAME = cvar.MED_GET_CELL_GEOMETRY_TYPENAME
MED_GET_FACE_GEOMETRY_TYPENAME = cvar.MED_GET_FACE_GEOMETRY_TYPENAME

MEDBOOL.__str__= lambda self: str([x for x in self])
MEDBOOL.__repr__= lambda self: "MEDBOOL("+str([x for x in self])+")"

class MEDFLOAT(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDFLOAT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDFLOAT, name)
    __repr__ = _swig_repr
    def iterator(self): return _medequivalence.MEDFLOAT_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medequivalence.MEDFLOAT___nonzero__(self)
    def __bool__(self): return _medequivalence.MEDFLOAT___bool__(self)
    def __len__(self): return _medequivalence.MEDFLOAT___len__(self)
    def pop(self): return _medequivalence.MEDFLOAT_pop(self)
    def __getslice__(self, *args): return _medequivalence.MEDFLOAT___getslice__(self, *args)
    def __setslice__(self, *args): return _medequivalence.MEDFLOAT___setslice__(self, *args)
    def __delslice__(self, *args): return _medequivalence.MEDFLOAT___delslice__(self, *args)
    def __delitem__(self, *args): return _medequivalence.MEDFLOAT___delitem__(self, *args)
    def __getitem__(self, *args): return _medequivalence.MEDFLOAT___getitem__(self, *args)
    def __setitem__(self, *args): return _medequivalence.MEDFLOAT___setitem__(self, *args)
    def append(self, *args): return _medequivalence.MEDFLOAT_append(self, *args)
    def empty(self): return _medequivalence.MEDFLOAT_empty(self)
    def size(self): return _medequivalence.MEDFLOAT_size(self)
    def clear(self): return _medequivalence.MEDFLOAT_clear(self)
    def swap(self, *args): return _medequivalence.MEDFLOAT_swap(self, *args)
    def get_allocator(self): return _medequivalence.MEDFLOAT_get_allocator(self)
    def begin(self): return _medequivalence.MEDFLOAT_begin(self)
    def end(self): return _medequivalence.MEDFLOAT_end(self)
    def rbegin(self): return _medequivalence.MEDFLOAT_rbegin(self)
    def rend(self): return _medequivalence.MEDFLOAT_rend(self)
    def pop_back(self): return _medequivalence.MEDFLOAT_pop_back(self)
    def erase(self, *args): return _medequivalence.MEDFLOAT_erase(self, *args)
    def __init__(self, *args): 
        this = _medequivalence.new_MEDFLOAT(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medequivalence.MEDFLOAT_push_back(self, *args)
    def front(self): return _medequivalence.MEDFLOAT_front(self)
    def back(self): return _medequivalence.MEDFLOAT_back(self)
    def assign(self, *args): return _medequivalence.MEDFLOAT_assign(self, *args)
    def resize(self, *args): return _medequivalence.MEDFLOAT_resize(self, *args)
    def insert(self, *args): return _medequivalence.MEDFLOAT_insert(self, *args)
    def reserve(self, *args): return _medequivalence.MEDFLOAT_reserve(self, *args)
    def capacity(self): return _medequivalence.MEDFLOAT_capacity(self)
    def __iadd__(self, *args): return _medequivalence.MEDFLOAT___iadd__(self, *args)
    def __add__(self, *args): return _medequivalence.MEDFLOAT___add__(self, *args)
    def __isub__(self, *args): return _medequivalence.MEDFLOAT___isub__(self, *args)
    def __sub__(self, *args): return _medequivalence.MEDFLOAT___sub__(self, *args)
    def __imul__(self, *args): return _medequivalence.MEDFLOAT___imul__(self, *args)
    def __mul__(self, *args): return _medequivalence.MEDFLOAT___mul__(self, *args)
    def __idiv__(self, *args): return _medequivalence.MEDFLOAT___idiv__(self, *args)
    def __div__(self, *args): return _medequivalence.MEDFLOAT___div__(self, *args)
    def __le__(self, *args): return _medequivalence.MEDFLOAT___le__(self, *args)
    def __lt__(self, *args): return _medequivalence.MEDFLOAT___lt__(self, *args)
    def __gt__(self, *args): return _medequivalence.MEDFLOAT___gt__(self, *args)
    def __ge__(self, *args): return _medequivalence.MEDFLOAT___ge__(self, *args)
    def __eq__(self, *args): return _medequivalence.MEDFLOAT___eq__(self, *args)
    def __ne__(self, *args): return _medequivalence.MEDFLOAT___ne__(self, *args)
    __swig_destroy__ = _medequivalence.delete_MEDFLOAT
    __del__ = lambda self : None;
MEDFLOAT_swigregister = _medequivalence.MEDFLOAT_swigregister
MEDFLOAT_swigregister(MEDFLOAT)

MEDFLOAT.__str__= lambda self: str([x for x in self])
MEDFLOAT.__repr__= lambda self:"MEDFLOAT" +"("+str([x for x in self])+")"

class MEDINT(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDINT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDINT, name)
    __repr__ = _swig_repr
    def iterator(self): return _medequivalence.MEDINT_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medequivalence.MEDINT___nonzero__(self)
    def __bool__(self): return _medequivalence.MEDINT___bool__(self)
    def __len__(self): return _medequivalence.MEDINT___len__(self)
    def pop(self): return _medequivalence.MEDINT_pop(self)
    def __getslice__(self, *args): return _medequivalence.MEDINT___getslice__(self, *args)
    def __setslice__(self, *args): return _medequivalence.MEDINT___setslice__(self, *args)
    def __delslice__(self, *args): return _medequivalence.MEDINT___delslice__(self, *args)
    def __delitem__(self, *args): return _medequivalence.MEDINT___delitem__(self, *args)
    def __getitem__(self, *args): return _medequivalence.MEDINT___getitem__(self, *args)
    def __setitem__(self, *args): return _medequivalence.MEDINT___setitem__(self, *args)
    def append(self, *args): return _medequivalence.MEDINT_append(self, *args)
    def empty(self): return _medequivalence.MEDINT_empty(self)
    def size(self): return _medequivalence.MEDINT_size(self)
    def clear(self): return _medequivalence.MEDINT_clear(self)
    def swap(self, *args): return _medequivalence.MEDINT_swap(self, *args)
    def get_allocator(self): return _medequivalence.MEDINT_get_allocator(self)
    def begin(self): return _medequivalence.MEDINT_begin(self)
    def end(self): return _medequivalence.MEDINT_end(self)
    def rbegin(self): return _medequivalence.MEDINT_rbegin(self)
    def rend(self): return _medequivalence.MEDINT_rend(self)
    def pop_back(self): return _medequivalence.MEDINT_pop_back(self)
    def erase(self, *args): return _medequivalence.MEDINT_erase(self, *args)
    def __init__(self, *args): 
        this = _medequivalence.new_MEDINT(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medequivalence.MEDINT_push_back(self, *args)
    def front(self): return _medequivalence.MEDINT_front(self)
    def back(self): return _medequivalence.MEDINT_back(self)
    def assign(self, *args): return _medequivalence.MEDINT_assign(self, *args)
    def resize(self, *args): return _medequivalence.MEDINT_resize(self, *args)
    def insert(self, *args): return _medequivalence.MEDINT_insert(self, *args)
    def reserve(self, *args): return _medequivalence.MEDINT_reserve(self, *args)
    def capacity(self): return _medequivalence.MEDINT_capacity(self)
    def __iadd__(self, *args): return _medequivalence.MEDINT___iadd__(self, *args)
    def __add__(self, *args): return _medequivalence.MEDINT___add__(self, *args)
    def __isub__(self, *args): return _medequivalence.MEDINT___isub__(self, *args)
    def __sub__(self, *args): return _medequivalence.MEDINT___sub__(self, *args)
    def __imul__(self, *args): return _medequivalence.MEDINT___imul__(self, *args)
    def __mul__(self, *args): return _medequivalence.MEDINT___mul__(self, *args)
    def __idiv__(self, *args): return _medequivalence.MEDINT___idiv__(self, *args)
    def __div__(self, *args): return _medequivalence.MEDINT___div__(self, *args)
    def __le__(self, *args): return _medequivalence.MEDINT___le__(self, *args)
    def __lt__(self, *args): return _medequivalence.MEDINT___lt__(self, *args)
    def __gt__(self, *args): return _medequivalence.MEDINT___gt__(self, *args)
    def __ge__(self, *args): return _medequivalence.MEDINT___ge__(self, *args)
    def __eq__(self, *args): return _medequivalence.MEDINT___eq__(self, *args)
    def __ne__(self, *args): return _medequivalence.MEDINT___ne__(self, *args)
    __swig_destroy__ = _medequivalence.delete_MEDINT
    __del__ = lambda self : None;
MEDINT_swigregister = _medequivalence.MEDINT_swigregister
MEDINT_swigregister(MEDINT)

MEDINT.__str__= lambda self: str([x for x in self])
MEDINT.__repr__= lambda self:"MEDINT" +"("+str([x for x in self])+")"

class MEDCHAR(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDCHAR, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDCHAR, name)
    __repr__ = _swig_repr
    def iterator(self): return _medequivalence.MEDCHAR_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medequivalence.MEDCHAR___nonzero__(self)
    def __bool__(self): return _medequivalence.MEDCHAR___bool__(self)
    def __len__(self): return _medequivalence.MEDCHAR___len__(self)
    def pop(self): return _medequivalence.MEDCHAR_pop(self)
    def __getslice__(self, *args): return _medequivalence.MEDCHAR___getslice__(self, *args)
    def __setslice__(self, *args): return _medequivalence.MEDCHAR___setslice__(self, *args)
    def __delslice__(self, *args): return _medequivalence.MEDCHAR___delslice__(self, *args)
    def __delitem__(self, *args): return _medequivalence.MEDCHAR___delitem__(self, *args)
    def __getitem__(self, *args): return _medequivalence.MEDCHAR___getitem__(self, *args)
    def __setitem__(self, *args): return _medequivalence.MEDCHAR___setitem__(self, *args)
    def append(self, *args): return _medequivalence.MEDCHAR_append(self, *args)
    def empty(self): return _medequivalence.MEDCHAR_empty(self)
    def size(self): return _medequivalence.MEDCHAR_size(self)
    def clear(self): return _medequivalence.MEDCHAR_clear(self)
    def swap(self, *args): return _medequivalence.MEDCHAR_swap(self, *args)
    def get_allocator(self): return _medequivalence.MEDCHAR_get_allocator(self)
    def begin(self): return _medequivalence.MEDCHAR_begin(self)
    def end(self): return _medequivalence.MEDCHAR_end(self)
    def rbegin(self): return _medequivalence.MEDCHAR_rbegin(self)
    def rend(self): return _medequivalence.MEDCHAR_rend(self)
    def pop_back(self): return _medequivalence.MEDCHAR_pop_back(self)
    def erase(self, *args): return _medequivalence.MEDCHAR_erase(self, *args)
    def __init__(self, *args): 
        this = _medequivalence.new_MEDCHAR(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medequivalence.MEDCHAR_push_back(self, *args)
    def front(self): return _medequivalence.MEDCHAR_front(self)
    def back(self): return _medequivalence.MEDCHAR_back(self)
    def assign(self, *args): return _medequivalence.MEDCHAR_assign(self, *args)
    def resize(self, *args): return _medequivalence.MEDCHAR_resize(self, *args)
    def insert(self, *args): return _medequivalence.MEDCHAR_insert(self, *args)
    def reserve(self, *args): return _medequivalence.MEDCHAR_reserve(self, *args)
    def capacity(self): return _medequivalence.MEDCHAR_capacity(self)
    def __iadd__(self, *args): return _medequivalence.MEDCHAR___iadd__(self, *args)
    def __add__(self, *args): return _medequivalence.MEDCHAR___add__(self, *args)
    def __isub__(self, *args): return _medequivalence.MEDCHAR___isub__(self, *args)
    def __sub__(self, *args): return _medequivalence.MEDCHAR___sub__(self, *args)
    def __imul__(self, *args): return _medequivalence.MEDCHAR___imul__(self, *args)
    def __mul__(self, *args): return _medequivalence.MEDCHAR___mul__(self, *args)
    def __idiv__(self, *args): return _medequivalence.MEDCHAR___idiv__(self, *args)
    def __div__(self, *args): return _medequivalence.MEDCHAR___div__(self, *args)
    def __le__(self, *args): return _medequivalence.MEDCHAR___le__(self, *args)
    def __lt__(self, *args): return _medequivalence.MEDCHAR___lt__(self, *args)
    def __gt__(self, *args): return _medequivalence.MEDCHAR___gt__(self, *args)
    def __ge__(self, *args): return _medequivalence.MEDCHAR___ge__(self, *args)
    def __eq__(self, *args): return _medequivalence.MEDCHAR___eq__(self, *args)
    def __ne__(self, *args): return _medequivalence.MEDCHAR___ne__(self, *args)
    __swig_destroy__ = _medequivalence.delete_MEDCHAR
    __del__ = lambda self : None;
MEDCHAR_swigregister = _medequivalence.MEDCHAR_swigregister
MEDCHAR_swigregister(MEDCHAR)

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"


def MEDequivalenceCr(*args, **kwargs):
  """
    MEDequivalenceCr(fid, meshname, equivname, description) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        equivname: char const *const
        description: char const *const

    """
  return _medequivalence.MEDequivalenceCr(*args, **kwargs)

def MEDequivalenceCorrespondenceWr(*args, **kwargs):
  """
    MEDequivalenceCorrespondenceWr(fid, meshname, equivname, numdt, numit, entitype, geotype, nentity, correspondence) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        equivname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        nentity: med_int const
        correspondence: med_int const *const

    """
  return _medequivalence.MEDequivalenceCorrespondenceWr(*args, **kwargs)

def MEDequivalenceCorrespondenceRd(*args, **kwargs):
  """
    MEDequivalenceCorrespondenceRd(fid, meshname, equivname, numdt, numit, entitype, geotype, correspondence) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        equivname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        correspondence: med_int *const

    """
  return _medequivalence.MEDequivalenceCorrespondenceRd(*args, **kwargs)

def MEDnEquivalence(*args, **kwargs):
  """
    MEDnEquivalence(fid, meshname) -> med_int

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medequivalence.MEDnEquivalence(*args, **kwargs)

def MEDequivalenceInfo(*args, **kwargs):
  """
    MEDequivalenceInfo(fid, meshname, equivit) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        equivit: int const

    """
  return _medequivalence.MEDequivalenceInfo(*args, **kwargs)

def MEDequivalenceComputingStepInfo(*args, **kwargs):
  """
    MEDequivalenceComputingStepInfo(fid, meshname, equivname, csit) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        equivname: char const *const
        csit: int const

    """
  return _medequivalence.MEDequivalenceComputingStepInfo(*args, **kwargs)

def MEDequivalenceCorrespondenceSizeInfo(*args, **kwargs):
  """
    MEDequivalenceCorrespondenceSizeInfo(fid, meshname, equivname, numdt, numit, corit, geotype) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        equivname: char const *const
        numdt: med_int const
        numit: med_int const
        corit: int const
        geotype: med_geometry_type *const

    """
  return _medequivalence.MEDequivalenceCorrespondenceSizeInfo(*args, **kwargs)

def MEDequivalenceCorrespondenceSize(*args, **kwargs):
  """
    MEDequivalenceCorrespondenceSize(fid, meshname, equivname, numdt, numit, entitype, geotype) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        equivname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const

    """
  return _medequivalence.MEDequivalenceCorrespondenceSize(*args, **kwargs)
# This file is compatible with both classic and new-style classes.


