# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_medmesh', [dirname(__file__)])
        except ImportError:
            import _medmesh
            return _medmesh
        if fp is not None:
            try:
                _mod = imp.load_module('_medmesh', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _medmesh = swig_import_helper()
    del swig_import_helper
else:
    import _medmesh
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator_medmesh_module(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator_medmesh_module, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator_medmesh_module, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _medmesh.delete_SwigPyIterator_medmesh_module
    __del__ = lambda self : None;
    def value(self): return _medmesh.SwigPyIterator_medmesh_module_value(self)
    def incr(self, n=1): return _medmesh.SwigPyIterator_medmesh_module_incr(self, n)
    def decr(self, n=1): return _medmesh.SwigPyIterator_medmesh_module_decr(self, n)
    def distance(self, *args): return _medmesh.SwigPyIterator_medmesh_module_distance(self, *args)
    def equal(self, *args): return _medmesh.SwigPyIterator_medmesh_module_equal(self, *args)
    def copy(self): return _medmesh.SwigPyIterator_medmesh_module_copy(self)
    def next(self): return _medmesh.SwigPyIterator_medmesh_module_next(self)
    def __next__(self): return _medmesh.SwigPyIterator_medmesh_module___next__(self)
    def previous(self): return _medmesh.SwigPyIterator_medmesh_module_previous(self)
    def advance(self, *args): return _medmesh.SwigPyIterator_medmesh_module_advance(self, *args)
    def __eq__(self, *args): return _medmesh.SwigPyIterator_medmesh_module___eq__(self, *args)
    def __ne__(self, *args): return _medmesh.SwigPyIterator_medmesh_module___ne__(self, *args)
    def __iadd__(self, *args): return _medmesh.SwigPyIterator_medmesh_module___iadd__(self, *args)
    def __isub__(self, *args): return _medmesh.SwigPyIterator_medmesh_module___isub__(self, *args)
    def __add__(self, *args): return _medmesh.SwigPyIterator_medmesh_module___add__(self, *args)
    def __sub__(self, *args): return _medmesh.SwigPyIterator_medmesh_module___sub__(self, *args)
    def __iter__(self): return self
    def __iter__(self): return self
SwigPyIterator_medmesh_module_swigregister = _medmesh.SwigPyIterator_medmesh_module_swigregister
SwigPyIterator_medmesh_module_swigregister(SwigPyIterator_medmesh_module)

ABSOLUTE_H5IPUBLIC_H = _medmesh.ABSOLUTE_H5IPUBLIC_H
ABSOLUTE_H5PUBLIC_H = _medmesh.ABSOLUTE_H5PUBLIC_H
HAVE_CC_C99 = _medmesh.HAVE_CC_C99
HAVE_CUSERID = _medmesh.HAVE_CUSERID
HAVE_DLFCN_H = _medmesh.HAVE_DLFCN_H
HAVE_FTIME = _medmesh.HAVE_FTIME
HAVE_GETEUID = _medmesh.HAVE_GETEUID
HAVE_GETPWUID = _medmesh.HAVE_GETPWUID
HAVE_GETTIMEOFDAY = _medmesh.HAVE_GETTIMEOFDAY
HAVE_H5IPUBLIC_H = _medmesh.HAVE_H5IPUBLIC_H
HAVE_H5PUBLIC_H = _medmesh.HAVE_H5PUBLIC_H
HAVE_INTTYPES_H = _medmesh.HAVE_INTTYPES_H
HAVE_LIBHDF5 = _medmesh.HAVE_LIBHDF5
HAVE_MALLOC_H = _medmesh.HAVE_MALLOC_H
HAVE_MEMORY_H = _medmesh.HAVE_MEMORY_H
HAVE_PWD_H = _medmesh.HAVE_PWD_H
HAVE_PYTHON = _medmesh.HAVE_PYTHON
HAVE_STDBOOL_H = _medmesh.HAVE_STDBOOL_H
HAVE_STDINT_H = _medmesh.HAVE_STDINT_H
HAVE_STDLIB_H = _medmesh.HAVE_STDLIB_H
HAVE_STRINGS_H = _medmesh.HAVE_STRINGS_H
HAVE_STRING_H = _medmesh.HAVE_STRING_H
HAVE_SYS_STAT_H = _medmesh.HAVE_SYS_STAT_H
HAVE_SYS_TIMEB_H = _medmesh.HAVE_SYS_TIMEB_H
HAVE_SYS_TIME_H = _medmesh.HAVE_SYS_TIME_H
HAVE_SYS_TYPES_H = _medmesh.HAVE_SYS_TYPES_H
HAVE_UNISTD_H = _medmesh.HAVE_UNISTD_H
HAVE__BOOL = _medmesh.HAVE__BOOL
LT_OBJDIR = _medmesh.LT_OBJDIR
MED_API_23 = _medmesh.MED_API_23
MED_CHECK_23FORMAT = _medmesh.MED_CHECK_23FORMAT
MED_HAVE_FORTRAN = _medmesh.MED_HAVE_FORTRAN
MED_HAVE_PYTHON = _medmesh.MED_HAVE_PYTHON
MESGERR = _medmesh.MESGERR
PACKAGE = _medmesh.PACKAGE
PACKAGE_BUGREPORT = _medmesh.PACKAGE_BUGREPORT
PACKAGE_NAME = _medmesh.PACKAGE_NAME
PACKAGE_STRING = _medmesh.PACKAGE_STRING
PACKAGE_TARNAME = _medmesh.PACKAGE_TARNAME
PACKAGE_URL = _medmesh.PACKAGE_URL
PACKAGE_VERSION = _medmesh.PACKAGE_VERSION
SIZEOF_FORTRAN_INTEGER = _medmesh.SIZEOF_FORTRAN_INTEGER
SIZEOF_INT = _medmesh.SIZEOF_INT
SIZEOF_LONG = _medmesh.SIZEOF_LONG
STDC_HEADERS = _medmesh.STDC_HEADERS
TIME_WITH_SYS_TIME = _medmesh.TIME_WITH_SYS_TIME
VERSION = _medmesh.VERSION
H5F_LIBVER_18 = _medmesh.H5F_LIBVER_18
MED_MAJOR_NUM = _medmesh.MED_MAJOR_NUM
MED_MINOR_NUM = _medmesh.MED_MINOR_NUM
MED_RELEASE_NUM = _medmesh.MED_RELEASE_NUM
MED_NUM_MAJEUR = _medmesh.MED_NUM_MAJEUR
MED_NUM_MINEUR = _medmesh.MED_NUM_MINEUR
MED_NUM_RELEASE = _medmesh.MED_NUM_RELEASE
MED_VERSION_STR = _medmesh.MED_VERSION_STR
MED_MAX_PARA = _medmesh.MED_MAX_PARA
MED_COMMENT_SIZE = _medmesh.MED_COMMENT_SIZE
MED_IDENT_SIZE = _medmesh.MED_IDENT_SIZE
MED_NAME_SIZE = _medmesh.MED_NAME_SIZE
MED_SNAME_SIZE = _medmesh.MED_SNAME_SIZE
MED_LNAME_SIZE = _medmesh.MED_LNAME_SIZE
MED_SNAME_BLANK = _medmesh.MED_SNAME_BLANK
MED_NAME_BLANK = _medmesh.MED_NAME_BLANK
MED_PATHNAME_SIZE = _medmesh.MED_PATHNAME_SIZE
MED_MAX_CHFID_PATH = _medmesh.MED_MAX_CHFID_PATH
MED_FULL_INTERLACE = _medmesh.MED_FULL_INTERLACE
MED_NO_INTERLACE = _medmesh.MED_NO_INTERLACE
MED_UNDEF_INTERLACE = _medmesh.MED_UNDEF_INTERLACE
MED_UNDEF_STMODE = _medmesh.MED_UNDEF_STMODE
MED_GLOBAL_STMODE = _medmesh.MED_GLOBAL_STMODE
MED_COMPACT_STMODE = _medmesh.MED_COMPACT_STMODE
MED_GLOBAL_PFLMODE = _medmesh.MED_GLOBAL_PFLMODE
MED_COMPACT_PFLMODE = _medmesh.MED_COMPACT_PFLMODE
MED_UNDEF_PFLMODE = _medmesh.MED_UNDEF_PFLMODE
MED_ACC_RDONLY = _medmesh.MED_ACC_RDONLY
MED_ACC_RDWR = _medmesh.MED_ACC_RDWR
MED_ACC_RDEXT = _medmesh.MED_ACC_RDEXT
MED_ACC_CREAT = _medmesh.MED_ACC_CREAT
MED_ACC_UNDEF = _medmesh.MED_ACC_UNDEF
MED_UNSTRUCTURED_MESH = _medmesh.MED_UNSTRUCTURED_MESH
MED_STRUCTURED_MESH = _medmesh.MED_STRUCTURED_MESH
MED_UNDEF_MESH_TYPE = _medmesh.MED_UNDEF_MESH_TYPE
MED_CARTESIAN_GRID = _medmesh.MED_CARTESIAN_GRID
MED_POLAR_GRID = _medmesh.MED_POLAR_GRID
MED_CURVILINEAR_GRID = _medmesh.MED_CURVILINEAR_GRID
MED_UNDEF_GRID_TYPE = _medmesh.MED_UNDEF_GRID_TYPE
MED_CELL = _medmesh.MED_CELL
MED_DESCENDING_FACE = _medmesh.MED_DESCENDING_FACE
MED_DESCENDING_EDGE = _medmesh.MED_DESCENDING_EDGE
MED_NODE = _medmesh.MED_NODE
MED_NODE_ELEMENT = _medmesh.MED_NODE_ELEMENT
MED_STRUCT_ELEMENT = _medmesh.MED_STRUCT_ELEMENT
MED_ALL_ENTITY_TYPE = _medmesh.MED_ALL_ENTITY_TYPE
MED_UNDEF_ENTITY_TYPE = _medmesh.MED_UNDEF_ENTITY_TYPE
MED_N_ENTITY_TYPES = _medmesh.MED_N_ENTITY_TYPES
MED_COORDINATE = _medmesh.MED_COORDINATE
MED_CONNECTIVITY = _medmesh.MED_CONNECTIVITY
MED_NAME = _medmesh.MED_NAME
MED_NUMBER = _medmesh.MED_NUMBER
MED_FAMILY_NUMBER = _medmesh.MED_FAMILY_NUMBER
MED_COORDINATE_AXIS1 = _medmesh.MED_COORDINATE_AXIS1
MED_COORDINATE_AXIS2 = _medmesh.MED_COORDINATE_AXIS2
MED_COORDINATE_AXIS3 = _medmesh.MED_COORDINATE_AXIS3
MED_INDEX_FACE = _medmesh.MED_INDEX_FACE
MED_INDEX_NODE = _medmesh.MED_INDEX_NODE
MED_GLOBAL_NUMBER = _medmesh.MED_GLOBAL_NUMBER
MED_VARIABLE_ATTRIBUTE = _medmesh.MED_VARIABLE_ATTRIBUTE
MED_COORDINATE_TRSF = _medmesh.MED_COORDINATE_TRSF
MED_UNDEF_DATATYPE = _medmesh.MED_UNDEF_DATATYPE
MED_INTERNAL_FLOAT64 = _medmesh.MED_INTERNAL_FLOAT64
MED_INTERNAL_INT32 = _medmesh.MED_INTERNAL_INT32
MED_INTERNAL_INT64 = _medmesh.MED_INTERNAL_INT64
MED_INTERNAL_INT = _medmesh.MED_INTERNAL_INT
MED_INTERNAL_NAME = _medmesh.MED_INTERNAL_NAME
MED_INTERNAL_SNAME = _medmesh.MED_INTERNAL_SNAME
MED_INTERNAL_LNAME = _medmesh.MED_INTERNAL_LNAME
MED_INTERNAL_IDENT = _medmesh.MED_INTERNAL_IDENT
MED_INTERNAL_CHAR = _medmesh.MED_INTERNAL_CHAR
MED_INTERNAL_UNDEF = _medmesh.MED_INTERNAL_UNDEF
MED_FLOAT64 = _medmesh.MED_FLOAT64
MED_INT32 = _medmesh.MED_INT32
MED_INT64 = _medmesh.MED_INT64
MED_INT = _medmesh.MED_INT
MED_ATT_FLOAT64 = _medmesh.MED_ATT_FLOAT64
MED_ATT_INT = _medmesh.MED_ATT_INT
MED_ATT_NAME = _medmesh.MED_ATT_NAME
MED_ATT_UNDEF = _medmesh.MED_ATT_UNDEF
MED_MESH = _medmesh.MED_MESH
MED_FIELD = _medmesh.MED_FIELD
MED_LIBRARY = _medmesh.MED_LIBRARY
MED_FILE = _medmesh.MED_FILE
MED_MESH_SUPPORT = _medmesh.MED_MESH_SUPPORT
MED_ELSTRUCT = _medmesh.MED_ELSTRUCT
MED_FAMILY = _medmesh.MED_FAMILY
MED_EQUIVALENCE = _medmesh.MED_EQUIVALENCE
MED_GROUP = _medmesh.MED_GROUP
MED_JOINT = _medmesh.MED_JOINT
MED_LOCALIZATION = _medmesh.MED_LOCALIZATION
MED_PROFILE = _medmesh.MED_PROFILE
MED_FILTER = _medmesh.MED_FILTER
MED_INTERPOLATION = _medmesh.MED_INTERPOLATION
MED_NUMERICAL_DATA = _medmesh.MED_NUMERICAL_DATA
MED_LINK = _medmesh.MED_LINK
MED_CLASS_UNDEF = _medmesh.MED_CLASS_UNDEF
MED_CLASS_ALL = _medmesh.MED_CLASS_ALL
MED_POINT1 = _medmesh.MED_POINT1
MED_SEG2 = _medmesh.MED_SEG2
MED_SEG3 = _medmesh.MED_SEG3
MED_SEG4 = _medmesh.MED_SEG4
MED_TRIA3 = _medmesh.MED_TRIA3
MED_QUAD4 = _medmesh.MED_QUAD4
MED_TRIA6 = _medmesh.MED_TRIA6
MED_TRIA7 = _medmesh.MED_TRIA7
MED_QUAD8 = _medmesh.MED_QUAD8
MED_QUAD9 = _medmesh.MED_QUAD9
MED_TETRA4 = _medmesh.MED_TETRA4
MED_PYRA5 = _medmesh.MED_PYRA5
MED_PENTA6 = _medmesh.MED_PENTA6
MED_HEXA8 = _medmesh.MED_HEXA8
MED_TETRA10 = _medmesh.MED_TETRA10
MED_OCTA12 = _medmesh.MED_OCTA12
MED_PYRA13 = _medmesh.MED_PYRA13
MED_PENTA15 = _medmesh.MED_PENTA15
MED_HEXA20 = _medmesh.MED_HEXA20
MED_HEXA27 = _medmesh.MED_HEXA27
MED_POLYGON = _medmesh.MED_POLYGON
MED_POLYGON2 = _medmesh.MED_POLYGON2
MED_POLYHEDRON = _medmesh.MED_POLYHEDRON
MED_STRUCT_GEO_INTERNAL = _medmesh.MED_STRUCT_GEO_INTERNAL
MED_STRUCT_GEO_SUP_INTERNAL = _medmesh.MED_STRUCT_GEO_SUP_INTERNAL
MED_NONE = _medmesh.MED_NONE
MED_NO_GEOTYPE = _medmesh.MED_NO_GEOTYPE
MED_UNDEF_GEOTYPE = _medmesh.MED_UNDEF_GEOTYPE
MED_UNDEF_GEOMETRY_TYPE = _medmesh.MED_UNDEF_GEOMETRY_TYPE
MED_ALL_GEOTYPE = _medmesh.MED_ALL_GEOTYPE
MED_GEO_ALL = _medmesh.MED_GEO_ALL
MED_N_CELL_GEO = _medmesh.MED_N_CELL_GEO
MED_N_CELL_FIXED_GEO = _medmesh.MED_N_CELL_FIXED_GEO
MED_N_CELL_GEO_FIXED_CON = _medmesh.MED_N_CELL_GEO_FIXED_CON
MED_N_FACE_GEO = _medmesh.MED_N_FACE_GEO
MED_N_FACE_FIXED_GEO = _medmesh.MED_N_FACE_FIXED_GEO
MED_N_FACE_GEO_FIXED_CON = _medmesh.MED_N_FACE_GEO_FIXED_CON
MED_N_EDGE_TYPES = _medmesh.MED_N_EDGE_TYPES
MED_N_EDGE_FIXED_GEO = _medmesh.MED_N_EDGE_FIXED_GEO
MED_N_EDGE_GEO_FIXED_CON = _medmesh.MED_N_EDGE_GEO_FIXED_CON
MED_N_NODE_GEO = _medmesh.MED_N_NODE_GEO
MED_N_NODE_FIXED_GEO = _medmesh.MED_N_NODE_FIXED_GEO
MED_N_NODE_GEO_FIXED_CON = _medmesh.MED_N_NODE_GEO_FIXED_CON
MED_NODAL = _medmesh.MED_NODAL
MED_DESCENDING = _medmesh.MED_DESCENDING
MED_UNDEF_CONNECTIVITY_MODE = _medmesh.MED_UNDEF_CONNECTIVITY_MODE
MED_NO_CMODE = _medmesh.MED_NO_CMODE
MED_CARTESIAN = _medmesh.MED_CARTESIAN
MED_CYLINDRICAL = _medmesh.MED_CYLINDRICAL
MED_SPHERICAL = _medmesh.MED_SPHERICAL
MED_UNDEF_AXIS_TYPE = _medmesh.MED_UNDEF_AXIS_TYPE
MED_FALSE = _medmesh.MED_FALSE
MED_TRUE = _medmesh.MED_TRUE
MED_GAUSS_ELNO = _medmesh.MED_GAUSS_ELNO
MED_IPOINT_ELNO = _medmesh.MED_IPOINT_ELNO
MED_NO_NAME = _medmesh.MED_NO_NAME
MED_NO_MESHNAME = _medmesh.MED_NO_MESHNAME
MED_NO_MESH = _medmesh.MED_NO_MESH
MED_NO_MESH_SUPPORT = _medmesh.MED_NO_MESH_SUPPORT
MED_NO_LOCALIZATION = _medmesh.MED_NO_LOCALIZATION
MED_NO_INTERPOLATION = _medmesh.MED_NO_INTERPOLATION
MED_NO_IPOINT_INTERNAL = _medmesh.MED_NO_IPOINT_INTERNAL
MED_NO_PROFILE = _medmesh.MED_NO_PROFILE
MED_NO_GROUP = _medmesh.MED_NO_GROUP
MED_ALLENTITIES_PROFILE = _medmesh.MED_ALLENTITIES_PROFILE
MED_NO_PROFILE_INTERNAL = _medmesh.MED_NO_PROFILE_INTERNAL
MED_SAME_PROFILE_INTERNAL = _medmesh.MED_SAME_PROFILE_INTERNAL
MED_ALL_CONSTITUENT = _medmesh.MED_ALL_CONSTITUENT
MED_UNDEF_SIZE = _medmesh.MED_UNDEF_SIZE
MED_NO_PROFILE_SIZE = _medmesh.MED_NO_PROFILE_SIZE
MED_SORT_DTIT = _medmesh.MED_SORT_DTIT
MED_SORT_ITDT = _medmesh.MED_SORT_ITDT
MED_SORT_UNDEF = _medmesh.MED_SORT_UNDEF
MED_NO_DT = _medmesh.MED_NO_DT
MED_NO_IT = _medmesh.MED_NO_IT
MED_UNDEF_DT = _medmesh.MED_UNDEF_DT
MED_ATT_NOT_FILLED = _medmesh.MED_ATT_NOT_FILLED
MED_MAX_FILTER_SPACES = _medmesh.MED_MAX_FILTER_SPACES
class med_filter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_filter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_filter, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nspaces"] = _medmesh.med_filter_nspaces_set
    __swig_getmethods__["nspaces"] = _medmesh.med_filter_nspaces_get
    if _newclass:nspaces = _swig_property(_medmesh.med_filter_nspaces_get, _medmesh.med_filter_nspaces_set)
    __swig_setmethods__["memspace"] = _medmesh.med_filter_memspace_set
    __swig_getmethods__["memspace"] = _medmesh.med_filter_memspace_get
    if _newclass:memspace = _swig_property(_medmesh.med_filter_memspace_get, _medmesh.med_filter_memspace_set)
    __swig_setmethods__["diskspace"] = _medmesh.med_filter_diskspace_set
    __swig_getmethods__["diskspace"] = _medmesh.med_filter_diskspace_get
    if _newclass:diskspace = _swig_property(_medmesh.med_filter_diskspace_get, _medmesh.med_filter_diskspace_set)
    __swig_setmethods__["nentity"] = _medmesh.med_filter_nentity_set
    __swig_getmethods__["nentity"] = _medmesh.med_filter_nentity_get
    if _newclass:nentity = _swig_property(_medmesh.med_filter_nentity_get, _medmesh.med_filter_nentity_set)
    __swig_setmethods__["nvaluesperentity"] = _medmesh.med_filter_nvaluesperentity_set
    __swig_getmethods__["nvaluesperentity"] = _medmesh.med_filter_nvaluesperentity_get
    if _newclass:nvaluesperentity = _swig_property(_medmesh.med_filter_nvaluesperentity_get, _medmesh.med_filter_nvaluesperentity_set)
    __swig_setmethods__["nconstituentpervalue"] = _medmesh.med_filter_nconstituentpervalue_set
    __swig_getmethods__["nconstituentpervalue"] = _medmesh.med_filter_nconstituentpervalue_get
    if _newclass:nconstituentpervalue = _swig_property(_medmesh.med_filter_nconstituentpervalue_get, _medmesh.med_filter_nconstituentpervalue_set)
    __swig_setmethods__["constituentselect"] = _medmesh.med_filter_constituentselect_set
    __swig_getmethods__["constituentselect"] = _medmesh.med_filter_constituentselect_get
    if _newclass:constituentselect = _swig_property(_medmesh.med_filter_constituentselect_get, _medmesh.med_filter_constituentselect_set)
    __swig_setmethods__["switchmode"] = _medmesh.med_filter_switchmode_set
    __swig_getmethods__["switchmode"] = _medmesh.med_filter_switchmode_get
    if _newclass:switchmode = _swig_property(_medmesh.med_filter_switchmode_get, _medmesh.med_filter_switchmode_set)
    __swig_setmethods__["filterarraysize"] = _medmesh.med_filter_filterarraysize_set
    __swig_getmethods__["filterarraysize"] = _medmesh.med_filter_filterarraysize_get
    if _newclass:filterarraysize = _swig_property(_medmesh.med_filter_filterarraysize_get, _medmesh.med_filter_filterarraysize_set)
    __swig_setmethods__["filterarray23v30"] = _medmesh.med_filter_filterarray23v30_set
    __swig_getmethods__["filterarray23v30"] = _medmesh.med_filter_filterarray23v30_get
    if _newclass:filterarray23v30 = _swig_property(_medmesh.med_filter_filterarray23v30_get, _medmesh.med_filter_filterarray23v30_set)
    __swig_setmethods__["profilearraysize"] = _medmesh.med_filter_profilearraysize_set
    __swig_getmethods__["profilearraysize"] = _medmesh.med_filter_profilearraysize_get
    if _newclass:profilearraysize = _swig_property(_medmesh.med_filter_profilearraysize_get, _medmesh.med_filter_profilearraysize_set)
    __swig_setmethods__["storagemode"] = _medmesh.med_filter_storagemode_set
    __swig_getmethods__["storagemode"] = _medmesh.med_filter_storagemode_get
    if _newclass:storagemode = _swig_property(_medmesh.med_filter_storagemode_get, _medmesh.med_filter_storagemode_set)
    __swig_setmethods__["profilename"] = _medmesh.med_filter_profilename_set
    __swig_getmethods__["profilename"] = _medmesh.med_filter_profilename_get
    if _newclass:profilename = _swig_property(_medmesh.med_filter_profilename_get, _medmesh.med_filter_profilename_set)
    def __init__(self): 
        """__init__(self) -> med_filter"""
        this = _medmesh.new_med_filter()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _medmesh.delete_med_filter
    __del__ = lambda self : None;
med_filter_swigregister = _medmesh.med_filter_swigregister
med_filter_swigregister(med_filter)

MED_NO_FILTER_SIZE = _medmesh.MED_NO_FILTER_SIZE
MED_NO_PROFILE_F = _medmesh.MED_NO_PROFILE_F
class med_file_version(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_file_version, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_file_version, name)
    __repr__ = _swig_repr
    __swig_setmethods__["majeur"] = _medmesh.med_file_version_majeur_set
    __swig_getmethods__["majeur"] = _medmesh.med_file_version_majeur_get
    if _newclass:majeur = _swig_property(_medmesh.med_file_version_majeur_get, _medmesh.med_file_version_majeur_set)
    __swig_setmethods__["mineur"] = _medmesh.med_file_version_mineur_set
    __swig_getmethods__["mineur"] = _medmesh.med_file_version_mineur_get
    if _newclass:mineur = _swig_property(_medmesh.med_file_version_mineur_get, _medmesh.med_file_version_mineur_set)
    __swig_setmethods__["release"] = _medmesh.med_file_version_release_set
    __swig_getmethods__["release"] = _medmesh.med_file_version_release_get
    if _newclass:release = _swig_property(_medmesh.med_file_version_release_get, _medmesh.med_file_version_release_set)
    def __init__(self): 
        """__init__(self) -> med_file_version"""
        this = _medmesh.new_med_file_version()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _medmesh.delete_med_file_version
    __del__ = lambda self : None;
med_file_version_swigregister = _medmesh.med_file_version_swigregister
med_file_version_swigregister(med_file_version)

class med_memfile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, med_memfile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, med_memfile, name)
    __repr__ = _swig_repr
    __swig_setmethods__["app_image_ptr"] = _medmesh.med_memfile_app_image_ptr_set
    __swig_getmethods__["app_image_ptr"] = _medmesh.med_memfile_app_image_ptr_get
    if _newclass:app_image_ptr = _swig_property(_medmesh.med_memfile_app_image_ptr_get, _medmesh.med_memfile_app_image_ptr_set)
    __swig_setmethods__["app_image_size"] = _medmesh.med_memfile_app_image_size_set
    __swig_getmethods__["app_image_size"] = _medmesh.med_memfile_app_image_size_get
    if _newclass:app_image_size = _swig_property(_medmesh.med_memfile_app_image_size_get, _medmesh.med_memfile_app_image_size_set)
    __swig_setmethods__["ref_count"] = _medmesh.med_memfile_ref_count_set
    __swig_getmethods__["ref_count"] = _medmesh.med_memfile_ref_count_get
    if _newclass:ref_count = _swig_property(_medmesh.med_memfile_ref_count_get, _medmesh.med_memfile_ref_count_set)
    __swig_setmethods__["fapl_image_ptr"] = _medmesh.med_memfile_fapl_image_ptr_set
    __swig_getmethods__["fapl_image_ptr"] = _medmesh.med_memfile_fapl_image_ptr_get
    if _newclass:fapl_image_ptr = _swig_property(_medmesh.med_memfile_fapl_image_ptr_get, _medmesh.med_memfile_fapl_image_ptr_set)
    __swig_setmethods__["fapl_image_size"] = _medmesh.med_memfile_fapl_image_size_set
    __swig_getmethods__["fapl_image_size"] = _medmesh.med_memfile_fapl_image_size_get
    if _newclass:fapl_image_size = _swig_property(_medmesh.med_memfile_fapl_image_size_get, _medmesh.med_memfile_fapl_image_size_set)
    __swig_setmethods__["fapl_ref_count"] = _medmesh.med_memfile_fapl_ref_count_set
    __swig_getmethods__["fapl_ref_count"] = _medmesh.med_memfile_fapl_ref_count_get
    if _newclass:fapl_ref_count = _swig_property(_medmesh.med_memfile_fapl_ref_count_get, _medmesh.med_memfile_fapl_ref_count_set)
    __swig_setmethods__["vfd_image_ptr"] = _medmesh.med_memfile_vfd_image_ptr_set
    __swig_getmethods__["vfd_image_ptr"] = _medmesh.med_memfile_vfd_image_ptr_get
    if _newclass:vfd_image_ptr = _swig_property(_medmesh.med_memfile_vfd_image_ptr_get, _medmesh.med_memfile_vfd_image_ptr_set)
    __swig_setmethods__["vfd_image_size"] = _medmesh.med_memfile_vfd_image_size_set
    __swig_getmethods__["vfd_image_size"] = _medmesh.med_memfile_vfd_image_size_get
    if _newclass:vfd_image_size = _swig_property(_medmesh.med_memfile_vfd_image_size_get, _medmesh.med_memfile_vfd_image_size_set)
    __swig_setmethods__["vfd_ref_count"] = _medmesh.med_memfile_vfd_ref_count_set
    __swig_getmethods__["vfd_ref_count"] = _medmesh.med_memfile_vfd_ref_count_get
    if _newclass:vfd_ref_count = _swig_property(_medmesh.med_memfile_vfd_ref_count_get, _medmesh.med_memfile_vfd_ref_count_set)
    __swig_setmethods__["flags"] = _medmesh.med_memfile_flags_set
    __swig_getmethods__["flags"] = _medmesh.med_memfile_flags_get
    if _newclass:flags = _swig_property(_medmesh.med_memfile_flags_get, _medmesh.med_memfile_flags_set)
    def __init__(self): 
        """__init__(self) -> med_memfile"""
        this = _medmesh.new_med_memfile()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _medmesh.delete_med_memfile
    __del__ = lambda self : None;
med_memfile_swigregister = _medmesh.med_memfile_swigregister
med_memfile_swigregister(med_memfile)

MED_PARTICLE_NAME = _medmesh.MED_PARTICLE_NAME
MED_BALL_NAME = _medmesh.MED_BALL_NAME
MED_BEAM_NAME = _medmesh.MED_BEAM_NAME
MED_PARTICLE_LABEL = _medmesh.MED_PARTICLE_LABEL
MED_BALL_DIAMETER = _medmesh.MED_BALL_DIAMETER
MED_BEAM_THICKNESS = _medmesh.MED_BEAM_THICKNESS
import medenum
class MEDBOOL(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDBOOL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDBOOL, name)
    __repr__ = _swig_repr
    def iterator(self): return _medmesh.MEDBOOL_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medmesh.MEDBOOL___nonzero__(self)
    def __bool__(self): return _medmesh.MEDBOOL___bool__(self)
    def __len__(self): return _medmesh.MEDBOOL___len__(self)
    def pop(self): return _medmesh.MEDBOOL_pop(self)
    def __getslice__(self, *args): return _medmesh.MEDBOOL___getslice__(self, *args)
    def __setslice__(self, *args): return _medmesh.MEDBOOL___setslice__(self, *args)
    def __delslice__(self, *args): return _medmesh.MEDBOOL___delslice__(self, *args)
    def __delitem__(self, *args): return _medmesh.MEDBOOL___delitem__(self, *args)
    def __getitem__(self, *args): return _medmesh.MEDBOOL___getitem__(self, *args)
    def __setitem__(self, *args): return _medmesh.MEDBOOL___setitem__(self, *args)
    def append(self, *args): return _medmesh.MEDBOOL_append(self, *args)
    def empty(self): return _medmesh.MEDBOOL_empty(self)
    def size(self): return _medmesh.MEDBOOL_size(self)
    def clear(self): return _medmesh.MEDBOOL_clear(self)
    def swap(self, *args): return _medmesh.MEDBOOL_swap(self, *args)
    def get_allocator(self): return _medmesh.MEDBOOL_get_allocator(self)
    def begin(self): return _medmesh.MEDBOOL_begin(self)
    def end(self): return _medmesh.MEDBOOL_end(self)
    def rbegin(self): return _medmesh.MEDBOOL_rbegin(self)
    def rend(self): return _medmesh.MEDBOOL_rend(self)
    def pop_back(self): return _medmesh.MEDBOOL_pop_back(self)
    def erase(self, *args): return _medmesh.MEDBOOL_erase(self, *args)
    def __init__(self, *args): 
        this = _medmesh.new_MEDBOOL(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medmesh.MEDBOOL_push_back(self, *args)
    def front(self): return _medmesh.MEDBOOL_front(self)
    def back(self): return _medmesh.MEDBOOL_back(self)
    def assign(self, *args): return _medmesh.MEDBOOL_assign(self, *args)
    def resize(self, *args): return _medmesh.MEDBOOL_resize(self, *args)
    def insert(self, *args): return _medmesh.MEDBOOL_insert(self, *args)
    def reserve(self, *args): return _medmesh.MEDBOOL_reserve(self, *args)
    def capacity(self): return _medmesh.MEDBOOL_capacity(self)
    __swig_destroy__ = _medmesh.delete_MEDBOOL
    __del__ = lambda self : None;
MEDBOOL_swigregister = _medmesh.MEDBOOL_swigregister
MEDBOOL_swigregister(MEDBOOL)
cvar = _medmesh.cvar
MED_GET_ENTITY_TYPENAME = cvar.MED_GET_ENTITY_TYPENAME
MED_GET_CELL_GEOMETRY_TYPENAME = cvar.MED_GET_CELL_GEOMETRY_TYPENAME
MED_GET_FACE_GEOMETRY_TYPENAME = cvar.MED_GET_FACE_GEOMETRY_TYPENAME

MEDBOOL.__str__= lambda self: str([x for x in self])
MEDBOOL.__repr__= lambda self: "MEDBOOL("+str([x for x in self])+")"

class MEDFLOAT(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDFLOAT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDFLOAT, name)
    __repr__ = _swig_repr
    def iterator(self): return _medmesh.MEDFLOAT_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medmesh.MEDFLOAT___nonzero__(self)
    def __bool__(self): return _medmesh.MEDFLOAT___bool__(self)
    def __len__(self): return _medmesh.MEDFLOAT___len__(self)
    def pop(self): return _medmesh.MEDFLOAT_pop(self)
    def __getslice__(self, *args): return _medmesh.MEDFLOAT___getslice__(self, *args)
    def __setslice__(self, *args): return _medmesh.MEDFLOAT___setslice__(self, *args)
    def __delslice__(self, *args): return _medmesh.MEDFLOAT___delslice__(self, *args)
    def __delitem__(self, *args): return _medmesh.MEDFLOAT___delitem__(self, *args)
    def __getitem__(self, *args): return _medmesh.MEDFLOAT___getitem__(self, *args)
    def __setitem__(self, *args): return _medmesh.MEDFLOAT___setitem__(self, *args)
    def append(self, *args): return _medmesh.MEDFLOAT_append(self, *args)
    def empty(self): return _medmesh.MEDFLOAT_empty(self)
    def size(self): return _medmesh.MEDFLOAT_size(self)
    def clear(self): return _medmesh.MEDFLOAT_clear(self)
    def swap(self, *args): return _medmesh.MEDFLOAT_swap(self, *args)
    def get_allocator(self): return _medmesh.MEDFLOAT_get_allocator(self)
    def begin(self): return _medmesh.MEDFLOAT_begin(self)
    def end(self): return _medmesh.MEDFLOAT_end(self)
    def rbegin(self): return _medmesh.MEDFLOAT_rbegin(self)
    def rend(self): return _medmesh.MEDFLOAT_rend(self)
    def pop_back(self): return _medmesh.MEDFLOAT_pop_back(self)
    def erase(self, *args): return _medmesh.MEDFLOAT_erase(self, *args)
    def __init__(self, *args): 
        this = _medmesh.new_MEDFLOAT(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medmesh.MEDFLOAT_push_back(self, *args)
    def front(self): return _medmesh.MEDFLOAT_front(self)
    def back(self): return _medmesh.MEDFLOAT_back(self)
    def assign(self, *args): return _medmesh.MEDFLOAT_assign(self, *args)
    def resize(self, *args): return _medmesh.MEDFLOAT_resize(self, *args)
    def insert(self, *args): return _medmesh.MEDFLOAT_insert(self, *args)
    def reserve(self, *args): return _medmesh.MEDFLOAT_reserve(self, *args)
    def capacity(self): return _medmesh.MEDFLOAT_capacity(self)
    def __iadd__(self, *args): return _medmesh.MEDFLOAT___iadd__(self, *args)
    def __add__(self, *args): return _medmesh.MEDFLOAT___add__(self, *args)
    def __isub__(self, *args): return _medmesh.MEDFLOAT___isub__(self, *args)
    def __sub__(self, *args): return _medmesh.MEDFLOAT___sub__(self, *args)
    def __imul__(self, *args): return _medmesh.MEDFLOAT___imul__(self, *args)
    def __mul__(self, *args): return _medmesh.MEDFLOAT___mul__(self, *args)
    def __idiv__(self, *args): return _medmesh.MEDFLOAT___idiv__(self, *args)
    def __div__(self, *args): return _medmesh.MEDFLOAT___div__(self, *args)
    def __le__(self, *args): return _medmesh.MEDFLOAT___le__(self, *args)
    def __lt__(self, *args): return _medmesh.MEDFLOAT___lt__(self, *args)
    def __gt__(self, *args): return _medmesh.MEDFLOAT___gt__(self, *args)
    def __ge__(self, *args): return _medmesh.MEDFLOAT___ge__(self, *args)
    def __eq__(self, *args): return _medmesh.MEDFLOAT___eq__(self, *args)
    def __ne__(self, *args): return _medmesh.MEDFLOAT___ne__(self, *args)
    __swig_destroy__ = _medmesh.delete_MEDFLOAT
    __del__ = lambda self : None;
MEDFLOAT_swigregister = _medmesh.MEDFLOAT_swigregister
MEDFLOAT_swigregister(MEDFLOAT)

MEDFLOAT.__str__= lambda self: str([x for x in self])
MEDFLOAT.__repr__= lambda self:"MEDFLOAT" +"("+str([x for x in self])+")"

class MEDINT(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDINT, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDINT, name)
    __repr__ = _swig_repr
    def iterator(self): return _medmesh.MEDINT_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medmesh.MEDINT___nonzero__(self)
    def __bool__(self): return _medmesh.MEDINT___bool__(self)
    def __len__(self): return _medmesh.MEDINT___len__(self)
    def pop(self): return _medmesh.MEDINT_pop(self)
    def __getslice__(self, *args): return _medmesh.MEDINT___getslice__(self, *args)
    def __setslice__(self, *args): return _medmesh.MEDINT___setslice__(self, *args)
    def __delslice__(self, *args): return _medmesh.MEDINT___delslice__(self, *args)
    def __delitem__(self, *args): return _medmesh.MEDINT___delitem__(self, *args)
    def __getitem__(self, *args): return _medmesh.MEDINT___getitem__(self, *args)
    def __setitem__(self, *args): return _medmesh.MEDINT___setitem__(self, *args)
    def append(self, *args): return _medmesh.MEDINT_append(self, *args)
    def empty(self): return _medmesh.MEDINT_empty(self)
    def size(self): return _medmesh.MEDINT_size(self)
    def clear(self): return _medmesh.MEDINT_clear(self)
    def swap(self, *args): return _medmesh.MEDINT_swap(self, *args)
    def get_allocator(self): return _medmesh.MEDINT_get_allocator(self)
    def begin(self): return _medmesh.MEDINT_begin(self)
    def end(self): return _medmesh.MEDINT_end(self)
    def rbegin(self): return _medmesh.MEDINT_rbegin(self)
    def rend(self): return _medmesh.MEDINT_rend(self)
    def pop_back(self): return _medmesh.MEDINT_pop_back(self)
    def erase(self, *args): return _medmesh.MEDINT_erase(self, *args)
    def __init__(self, *args): 
        this = _medmesh.new_MEDINT(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medmesh.MEDINT_push_back(self, *args)
    def front(self): return _medmesh.MEDINT_front(self)
    def back(self): return _medmesh.MEDINT_back(self)
    def assign(self, *args): return _medmesh.MEDINT_assign(self, *args)
    def resize(self, *args): return _medmesh.MEDINT_resize(self, *args)
    def insert(self, *args): return _medmesh.MEDINT_insert(self, *args)
    def reserve(self, *args): return _medmesh.MEDINT_reserve(self, *args)
    def capacity(self): return _medmesh.MEDINT_capacity(self)
    def __iadd__(self, *args): return _medmesh.MEDINT___iadd__(self, *args)
    def __add__(self, *args): return _medmesh.MEDINT___add__(self, *args)
    def __isub__(self, *args): return _medmesh.MEDINT___isub__(self, *args)
    def __sub__(self, *args): return _medmesh.MEDINT___sub__(self, *args)
    def __imul__(self, *args): return _medmesh.MEDINT___imul__(self, *args)
    def __mul__(self, *args): return _medmesh.MEDINT___mul__(self, *args)
    def __idiv__(self, *args): return _medmesh.MEDINT___idiv__(self, *args)
    def __div__(self, *args): return _medmesh.MEDINT___div__(self, *args)
    def __le__(self, *args): return _medmesh.MEDINT___le__(self, *args)
    def __lt__(self, *args): return _medmesh.MEDINT___lt__(self, *args)
    def __gt__(self, *args): return _medmesh.MEDINT___gt__(self, *args)
    def __ge__(self, *args): return _medmesh.MEDINT___ge__(self, *args)
    def __eq__(self, *args): return _medmesh.MEDINT___eq__(self, *args)
    def __ne__(self, *args): return _medmesh.MEDINT___ne__(self, *args)
    __swig_destroy__ = _medmesh.delete_MEDINT
    __del__ = lambda self : None;
MEDINT_swigregister = _medmesh.MEDINT_swigregister
MEDINT_swigregister(MEDINT)

MEDINT.__str__= lambda self: str([x for x in self])
MEDINT.__repr__= lambda self:"MEDINT" +"("+str([x for x in self])+")"

class MEDCHAR(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MEDCHAR, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MEDCHAR, name)
    __repr__ = _swig_repr
    def iterator(self): return _medmesh.MEDCHAR_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _medmesh.MEDCHAR___nonzero__(self)
    def __bool__(self): return _medmesh.MEDCHAR___bool__(self)
    def __len__(self): return _medmesh.MEDCHAR___len__(self)
    def pop(self): return _medmesh.MEDCHAR_pop(self)
    def __getslice__(self, *args): return _medmesh.MEDCHAR___getslice__(self, *args)
    def __setslice__(self, *args): return _medmesh.MEDCHAR___setslice__(self, *args)
    def __delslice__(self, *args): return _medmesh.MEDCHAR___delslice__(self, *args)
    def __delitem__(self, *args): return _medmesh.MEDCHAR___delitem__(self, *args)
    def __getitem__(self, *args): return _medmesh.MEDCHAR___getitem__(self, *args)
    def __setitem__(self, *args): return _medmesh.MEDCHAR___setitem__(self, *args)
    def append(self, *args): return _medmesh.MEDCHAR_append(self, *args)
    def empty(self): return _medmesh.MEDCHAR_empty(self)
    def size(self): return _medmesh.MEDCHAR_size(self)
    def clear(self): return _medmesh.MEDCHAR_clear(self)
    def swap(self, *args): return _medmesh.MEDCHAR_swap(self, *args)
    def get_allocator(self): return _medmesh.MEDCHAR_get_allocator(self)
    def begin(self): return _medmesh.MEDCHAR_begin(self)
    def end(self): return _medmesh.MEDCHAR_end(self)
    def rbegin(self): return _medmesh.MEDCHAR_rbegin(self)
    def rend(self): return _medmesh.MEDCHAR_rend(self)
    def pop_back(self): return _medmesh.MEDCHAR_pop_back(self)
    def erase(self, *args): return _medmesh.MEDCHAR_erase(self, *args)
    def __init__(self, *args): 
        this = _medmesh.new_MEDCHAR(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _medmesh.MEDCHAR_push_back(self, *args)
    def front(self): return _medmesh.MEDCHAR_front(self)
    def back(self): return _medmesh.MEDCHAR_back(self)
    def assign(self, *args): return _medmesh.MEDCHAR_assign(self, *args)
    def resize(self, *args): return _medmesh.MEDCHAR_resize(self, *args)
    def insert(self, *args): return _medmesh.MEDCHAR_insert(self, *args)
    def reserve(self, *args): return _medmesh.MEDCHAR_reserve(self, *args)
    def capacity(self): return _medmesh.MEDCHAR_capacity(self)
    def __iadd__(self, *args): return _medmesh.MEDCHAR___iadd__(self, *args)
    def __add__(self, *args): return _medmesh.MEDCHAR___add__(self, *args)
    def __isub__(self, *args): return _medmesh.MEDCHAR___isub__(self, *args)
    def __sub__(self, *args): return _medmesh.MEDCHAR___sub__(self, *args)
    def __imul__(self, *args): return _medmesh.MEDCHAR___imul__(self, *args)
    def __mul__(self, *args): return _medmesh.MEDCHAR___mul__(self, *args)
    def __idiv__(self, *args): return _medmesh.MEDCHAR___idiv__(self, *args)
    def __div__(self, *args): return _medmesh.MEDCHAR___div__(self, *args)
    def __le__(self, *args): return _medmesh.MEDCHAR___le__(self, *args)
    def __lt__(self, *args): return _medmesh.MEDCHAR___lt__(self, *args)
    def __gt__(self, *args): return _medmesh.MEDCHAR___gt__(self, *args)
    def __ge__(self, *args): return _medmesh.MEDCHAR___ge__(self, *args)
    def __eq__(self, *args): return _medmesh.MEDCHAR___eq__(self, *args)
    def __ne__(self, *args): return _medmesh.MEDCHAR___ne__(self, *args)
    __swig_destroy__ = _medmesh.delete_MEDCHAR
    __del__ = lambda self : None;
MEDCHAR_swigregister = _medmesh.MEDCHAR_swigregister
MEDCHAR_swigregister(MEDCHAR)

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"

MEDCHAR.__str__= lambda self: str([x for x in self])
MEDCHAR.__repr__= lambda self:"MEDCHAR" +"("+str([x for x in self])+")"


def MEDmeshCr(*args, **kwargs):
  """
    MEDmeshCr(fid, meshname, spacedim, meshdim, meshtype, description, dtunit, sortingtype, axistype, 
        axisname, axisunit) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        spacedim: med_int const
        meshdim: med_int const
        meshtype: enum med_mesh_type const
        description: char const *const
        dtunit: char const *const
        sortingtype: enum med_sorting_type const
        axistype: enum med_axis_type const
        axisname: char const *const
        axisunit: char const *const


    Essai d Ajout a La Documentation Automatique
    """
  return _medmesh.MEDmeshCr(*args, **kwargs)

def MEDmeshInfoByName(*args, **kwargs):
  """
    MEDmeshInfoByName(fid, meshname) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medmesh.MEDmeshInfoByName(*args, **kwargs)

def MEDmeshInfo(*args, **kwargs):
  """
    MEDmeshInfo(fid, meshit) -> med_err

    Parameters:
        fid: med_idt const
        meshit: int const

    """
  return _medmesh.MEDmeshInfo(*args, **kwargs)

def MEDnMesh(*args, **kwargs):
  """
    MEDnMesh(fid) -> med_int

    Parameters:
        fid: med_idt const

    """
  return _medmesh.MEDnMesh(*args, **kwargs)

def MEDmeshnAxis(*args, **kwargs):
  """
    MEDmeshnAxis(fid, meshit) -> med_int

    Parameters:
        fid: med_idt const
        meshit: int const

    """
  return _medmesh.MEDmeshnAxis(*args, **kwargs)

def MEDmeshnAxisByName(*args, **kwargs):
  """
    MEDmeshnAxisByName(fid, meshname) -> med_int

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medmesh.MEDmeshnAxisByName(*args, **kwargs)

def MEDmeshGridTypeWr(*args, **kwargs):
  """
    MEDmeshGridTypeWr(fid, meshname, gridtype) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        gridtype: enum med_grid_type const

    """
  return _medmesh.MEDmeshGridTypeWr(*args, **kwargs)

def MEDmeshGridTypeRd(*args, **kwargs):
  """
    MEDmeshGridTypeRd(fid, meshname) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medmesh.MEDmeshGridTypeRd(*args, **kwargs)

def MEDmeshGridIndexCoordinateWr(*args, **kwargs):
  """
    MEDmeshGridIndexCoordinateWr(fid, meshname, numdt, numit, dt, axis, indexsize, gridindex) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        axis: med_int const
        indexsize: med_int const
        gridindex: med_float const *const

    """
  return _medmesh.MEDmeshGridIndexCoordinateWr(*args, **kwargs)

def MEDmeshGridIndexCoordinateRd(*args, **kwargs):
  """
    MEDmeshGridIndexCoordinateRd(fid, meshname, numdt, numit, axis, gridindex) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        axis: med_int const
        gridindex: med_float *const

    """
  return _medmesh.MEDmeshGridIndexCoordinateRd(*args, **kwargs)

def MEDmeshGridStructWr(*args, **kwargs):
  """
    MEDmeshGridStructWr(fid, meshname, numdt, numit, dt, gridstruct) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        gridstruct: med_int const *const

    """
  return _medmesh.MEDmeshGridStructWr(*args, **kwargs)

def MEDmeshGridStructRd(*args, **kwargs):
  """
    MEDmeshGridStructRd(fid, meshname, numdt, numit, gridstruct) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        gridstruct: med_int *const

    """
  return _medmesh.MEDmeshGridStructRd(*args, **kwargs)

def MEDmeshUniversalNameWr(*args, **kwargs):
  """
    MEDmeshUniversalNameWr(fid, meshname) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medmesh.MEDmeshUniversalNameWr(*args, **kwargs)

def MEDmeshUniversalNameRd(*args, **kwargs):
  """
    MEDmeshUniversalNameRd(fid, meshname) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medmesh.MEDmeshUniversalNameRd(*args, **kwargs)

def MEDmeshComputationStepCr(*args, **kwargs):
  """
    MEDmeshComputationStepCr(fid, meshname, numdt1, numit1, numdt2, numit2, dt2) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt1: med_int const
        numit1: med_int const
        numdt2: med_int const
        numit2: med_int const
        dt2: med_float const

    """
  return _medmesh.MEDmeshComputationStepCr(*args, **kwargs)

def MEDmeshAttributeRd(*args, **kwargs):
  """
    MEDmeshAttributeRd(fid, meshname) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medmesh.MEDmeshAttributeRd(*args, **kwargs)

def MEDmeshAttributeWr(*args, **kwargs):
  """
    MEDmeshAttributeWr(fid, meshname, isolatednodes, verticesnodes, cellmaxnodes) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        isolatednodes: med_int const
        verticesnodes: med_int const
        cellmaxnodes: med_int const

    """
  return _medmesh.MEDmeshAttributeWr(*args, **kwargs)

def MEDmeshComputationStepDtRd(*args, **kwargs):
  """
    MEDmeshComputationStepDtRd(fid, meshname, numdt, umit) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        umit: med_int const

    """
  return _medmesh.MEDmeshComputationStepDtRd(*args, **kwargs)

def MEDmeshComputationStepInfo(*args, **kwargs):
  """
    MEDmeshComputationStepInfo(fid, meshname, csit) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        csit: int const

    """
  return _medmesh.MEDmeshComputationStepInfo(*args, **kwargs)

def MEDmeshSortingTypeRd(*args, **kwargs):
  """
    MEDmeshSortingTypeRd(fid, meshname) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const

    """
  return _medmesh.MEDmeshSortingTypeRd(*args, **kwargs)

def MEDmeshNodeCoordinateAdvancedWr(*args, **kwargs):
  """
    MEDmeshNodeCoordinateAdvancedWr(fid, meshname, numdt, numit, dt, filter, value) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        filter: med_filter const *const
        value: med_float const *const

    """
  return _medmesh.MEDmeshNodeCoordinateAdvancedWr(*args, **kwargs)

def MEDmeshNodeCoordinateWithProfileWr(*args, **kwargs):
  """
    MEDmeshNodeCoordinateWithProfileWr(fid, meshname, numdt, numit, dt, storagemode, profilename, switchmode, dimselect, 
        nentity, coordinates) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        storagemode: enum med_storage_mode const
        profilename: char const *const
        switchmode: enum med_switch_mode const
        dimselect: med_int const
        nentity: med_int const
        coordinates: med_float const *const

    """
  return _medmesh.MEDmeshNodeCoordinateWithProfileWr(*args, **kwargs)

def MEDmeshNodeCoordinateWr(*args, **kwargs):
  """
    MEDmeshNodeCoordinateWr(fid, meshname, numdt, numit, dt, switchmode, nentity, coordinates) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        switchmode: enum med_switch_mode const
        nentity: med_int const
        coordinates: med_float const *const

    """
  return _medmesh.MEDmeshNodeCoordinateWr(*args, **kwargs)

def MEDmeshNodeCoordinateTrsfWr(*args, **kwargs):
  """
    MEDmeshNodeCoordinateTrsfWr(fid, meshname, numdt, numit, dt, coordinatetrsf) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        coordinatetrsf: med_float const *const

    """
  return _medmesh.MEDmeshNodeCoordinateTrsfWr(*args, **kwargs)

def MEDmeshNodeCoordinateTrsfRd(*args, **kwargs):
  """
    MEDmeshNodeCoordinateTrsfRd(fid, meshname, numdt, numit, coordinatetrsf) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        coordinatetrsf: med_float const *const

    """
  return _medmesh.MEDmeshNodeCoordinateTrsfRd(*args, **kwargs)

def MEDmeshElementConnectivityWr(*args, **kwargs):
  """
    MEDmeshElementConnectivityWr(fid, meshname, numdt, numit, dt, entitype, geotype, cmode, switchmode, nentity, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        switchmode: enum med_switch_mode const
        nentity: med_int const
        connectivity: med_int const *const

    """
  return _medmesh.MEDmeshElementConnectivityWr(*args, **kwargs)

def MEDmeshElementConnectivityAdvancedWr(*args, **kwargs):
  """
    MEDmeshElementConnectivityAdvancedWr(fid, meshname, numdt, numit, dt, entitype, geotype, cmode, filter, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        filter: med_filter const *const
        connectivity: med_int const *const

    """
  return _medmesh.MEDmeshElementConnectivityAdvancedWr(*args, **kwargs)

def MEDmeshElementConnectivityWithProfileWr(*args, **kwargs):
  """
    MEDmeshElementConnectivityWithProfileWr(fid, meshname, numdt, numit, dt, entitype, geotype, cmode, storagemode, profilename, 
        switchmode, dimselect, nentity, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        storagemode: enum med_storage_mode const
        profilename: char const *const
        switchmode: enum med_switch_mode const
        dimselect: med_int const
        nentity: med_int const
        connectivity: med_int const *const

    """
  return _medmesh.MEDmeshElementConnectivityWithProfileWr(*args, **kwargs)

def MEDmeshNodeCoordinateAdvancedRd(*args, **kwargs):
  """
    MEDmeshNodeCoordinateAdvancedRd(fid, meshname, numdt, numit, filter, value) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        filter: med_filter const *const
        value: med_float *const

    """
  return _medmesh.MEDmeshNodeCoordinateAdvancedRd(*args, **kwargs)

def MEDmeshNodeCoordinateWithProfileRd(*args, **kwargs):
  """
    MEDmeshNodeCoordinateWithProfileRd(fid, meshname, numdt, numit, storagemode, profilename, switchmode, dimselect, coordinates) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        storagemode: enum med_storage_mode const
        profilename: char const *const
        switchmode: enum med_switch_mode const
        dimselect: med_int const
        coordinates: med_float *const

    """
  return _medmesh.MEDmeshNodeCoordinateWithProfileRd(*args, **kwargs)

def MEDmeshNodeCoordinateRd(*args, **kwargs):
  """
    MEDmeshNodeCoordinateRd(fid, meshname, numdt, numit, switchmode, coordinates) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        switchmode: enum med_switch_mode const
        coordinates: med_float *const

    """
  return _medmesh.MEDmeshNodeCoordinateRd(*args, **kwargs)

def MEDmeshElementConnectivityRd(*args, **kwargs):
  """
    MEDmeshElementConnectivityRd(fid, meshname, numdt, numit, entitype, geotype, cmode, switchmode, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        switchmode: enum med_switch_mode const
        connectivity: med_int *const

    """
  return _medmesh.MEDmeshElementConnectivityRd(*args, **kwargs)

def MEDmeshElementConnectivityAdvancedRd(*args, **kwargs):
  """
    MEDmeshElementConnectivityAdvancedRd(fid, meshname, numdt, numit, entitype, geotype, cmode, filter, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        filter: med_filter const *const
        connectivity: med_int *const

    """
  return _medmesh.MEDmeshElementConnectivityAdvancedRd(*args, **kwargs)

def MEDmeshElementConnectivityWithProfileRd(*args, **kwargs):
  """
    MEDmeshElementConnectivityWithProfileRd(fid, meshname, numdt, numit, entitype, geotype, cmode, storagemode, profilename, 
        switchmode, dimselect, nentity, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        storagemode: enum med_storage_mode const
        profilename: char const *const
        switchmode: enum med_switch_mode const
        dimselect: med_int const
        nentity: med_int const
        connectivity: med_int *const

    """
  return _medmesh.MEDmeshElementConnectivityWithProfileRd(*args, **kwargs)

def MEDmeshnEntity(*args, **kwargs):
  """
    MEDmeshnEntity(fid, meshname, numdt, numit, entitype, geotype, datatype, cmode) -> med_int

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        datatype: enum med_data_type const
        cmode: enum med_connectivity_mode const

    """
  return _medmesh.MEDmeshnEntity(*args, **kwargs)

def MEDmeshnEntityWithProfile(*args, **kwargs):
  """
    MEDmeshnEntityWithProfile(fid, meshname, numdt, numit, entitype, geotype, datatype, cmode, storagemode) -> med_int

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        datatype: enum med_data_type const
        cmode: enum med_connectivity_mode const
        storagemode: enum med_storage_mode const

    """
  return _medmesh.MEDmeshnEntityWithProfile(*args, **kwargs)

def MEDmeshEntityInfo(*args, **kwargs):
  """
    MEDmeshEntityInfo(fid, meshname, numdt, numit, entitype, geotypeit, geotype) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotypeit: int const
        geotype: med_geometry_type *const

    """
  return _medmesh.MEDmeshEntityInfo(*args, **kwargs)

def MEDmeshEntityNameWr(*args, **kwargs):
  """
    MEDmeshEntityNameWr(fid, meshname, numdt, numit, entitype, geotype, nentity, name) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        nentity: med_int const
        name: char const *const

    """
  return _medmesh.MEDmeshEntityNameWr(*args, **kwargs)

def MEDmeshEntityNameRd(*args, **kwargs):
  """
    MEDmeshEntityNameRd(fid, meshname, numdt, numit, entitype, geotype, name) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        name: char *const

    """
  return _medmesh.MEDmeshEntityNameRd(*args, **kwargs)

def MEDmeshEntityNumberWr(*args, **kwargs):
  """
    MEDmeshEntityNumberWr(fid, meshname, numdt, numit, entitype, geotype, nentity, number) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        nentity: med_int const
        number: med_int const *const

    """
  return _medmesh.MEDmeshEntityNumberWr(*args, **kwargs)

def MEDmeshEntityNumberRd(*args, **kwargs):
  """
    MEDmeshEntityNumberRd(fid, meshname, numdt, numit, entitype, geotype, number) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        number: med_int *const

    """
  return _medmesh.MEDmeshEntityNumberRd(*args, **kwargs)

def MEDmeshEntityFamilyNumberWr(*args, **kwargs):
  """
    MEDmeshEntityFamilyNumberWr(fid, meshname, numdt, numit, entitype, geotype, nentity, number) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        nentity: med_int const
        number: med_int const *const

    """
  return _medmesh.MEDmeshEntityFamilyNumberWr(*args, **kwargs)

def MEDmeshEntityFamilyNumberRd(*args, **kwargs):
  """
    MEDmeshEntityFamilyNumberRd(fid, meshname, numdt, numit, entitype, geotype, number) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        number: med_int *const

    """
  return _medmesh.MEDmeshEntityFamilyNumberRd(*args, **kwargs)

def MEDmeshEntityAttributeAdvancedRd(*args, **kwargs):
  """
    MEDmeshEntityAttributeAdvancedRd(fid, meshname, datatype, numdt, numit, entitype, geotype, filter, attval) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        datatype: enum med_data_type const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        filter: med_filter const *const
        attval: void *const

    """
  return _medmesh.MEDmeshEntityAttributeAdvancedRd(*args, **kwargs)

def MEDmeshEntityAttributeAdvancedWr(*args, **kwargs):
  """
    MEDmeshEntityAttributeAdvancedWr(fid, meshname, datatype, numdt, numit, entitype, geotype, filter, attval) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        datatype: enum med_data_type const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        filter: med_filter const *const
        attval: void const *const

    """
  return _medmesh.MEDmeshEntityAttributeAdvancedWr(*args, **kwargs)

def MEDmeshPolygonWr(*args, **kwargs):
  """
    MEDmeshPolygonWr(fid, meshname, numdt, numit, dt, entitype, cmode, indexsize, polyindex, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        entitype: enum med_entity_type const
        cmode: enum med_connectivity_mode const
        indexsize: med_int const
        polyindex: med_int const *const
        connectivity: med_int const *const

    """
  return _medmesh.MEDmeshPolygonWr(*args, **kwargs)

def MEDmeshPolygon2Wr(*args, **kwargs):
  """
    MEDmeshPolygon2Wr(fid, meshname, numdt, numit, dt, entitype, polytype, cmode, indexsize, polyindex, 
        connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        entitype: enum med_entity_type const
        polytype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        indexsize: med_int const
        polyindex: med_int const *const
        connectivity: med_int const *const

    """
  return _medmesh.MEDmeshPolygon2Wr(*args, **kwargs)

def MEDmeshPolygonRd(*args, **kwargs):
  """
    MEDmeshPolygonRd(fid, meshname, numdt, numit, entitype, cmode, polyindex, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        cmode: enum med_connectivity_mode const
        polyindex: med_int *const
        connectivity: med_int *const

    """
  return _medmesh.MEDmeshPolygonRd(*args, **kwargs)

def MEDmeshPolygon2Rd(*args, **kwargs):
  """
    MEDmeshPolygon2Rd(fid, meshname, numdt, numit, entitype, polytype, cmode, polyindex, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        polytype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        polyindex: med_int *const
        connectivity: med_int *const

    """
  return _medmesh.MEDmeshPolygon2Rd(*args, **kwargs)

def MEDmeshPolyhedronRd(*args, **kwargs):
  """
    MEDmeshPolyhedronRd(fid, meshname, numdt, numit, entitype, cmode, faceindex, nodeindex, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        cmode: enum med_connectivity_mode const
        faceindex: med_int *const
        nodeindex: med_int *const
        connectivity: med_int *const

    """
  return _medmesh.MEDmeshPolyhedronRd(*args, **kwargs)

def MEDmeshPolyhedronWr(*args, **kwargs):
  """
    MEDmeshPolyhedronWr(fid, meshname, numdt, numit, dt, entitype, cmode, faceindexsize, faceindex, nodeindexsize, 
        nodeindex, connectivity) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        entitype: enum med_entity_type const
        cmode: enum med_connectivity_mode const
        faceindexsize: med_int const
        faceindex: med_int const *const
        nodeindexsize: med_int const
        nodeindex: med_int const *const
        connectivity: med_int const *const

    """
  return _medmesh.MEDmeshPolyhedronWr(*args, **kwargs)

def MEDmeshGeotypeName(*args, **kwargs):
  """
    MEDmeshGeotypeName(fid, geotype) -> med_err

    Parameters:
        fid: med_idt const
        geotype: med_geometry_type const

    """
  return _medmesh.MEDmeshGeotypeName(*args, **kwargs)

def MEDmeshGeotypeParameter(*args, **kwargs):
  """
    MEDmeshGeotypeParameter(fid, geotype) -> med_err

    Parameters:
        fid: med_idt const
        geotype: med_geometry_type const

    """
  return _medmesh.MEDmeshGeotypeParameter(*args, **kwargs)

def MEDmeshGlobalNumberWr(*args, **kwargs):
  """
    MEDmeshGlobalNumberWr(fid, meshname, numdt, numit, entitytype, geotype, nentity, number) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitytype: enum med_entity_type const
        geotype: med_geometry_type const
        nentity: med_int const
        number: med_int const *const

    """
  return _medmesh.MEDmeshGlobalNumberWr(*args, **kwargs)

def MEDmeshGlobalNumberRd(*args, **kwargs):
  """
    MEDmeshGlobalNumberRd(fid, meshname, numdt, numit, entitytype, geotype, number) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitytype: enum med_entity_type const
        geotype: med_geometry_type const
        number: med_int *const

    """
  return _medmesh.MEDmeshGlobalNumberRd(*args, **kwargs)

def MEDmeshNodeWr(*args, **kwargs):
  """
    MEDmeshNodeWr(fid, meshname, numdt, numit, dt, switchmode, nentity, coordinate, withnodename, nodename, 
        withnodenumber, nodenumber, withfamnumber, famnumber) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        switchmode: enum med_switch_mode const
        nentity: med_int const
        coordinate: med_float const *const
        withnodename: enum med_bool const
        nodename: char const *const
        withnodenumber: enum med_bool const
        nodenumber: med_int const *const
        withfamnumber: enum med_bool const
        famnumber: med_int const *const

    """
  return _medmesh.MEDmeshNodeWr(*args, **kwargs)

def MEDmeshNodeRd(*args, **kwargs):
  """
    MEDmeshNodeRd(fid, meshname, numdt, numit, switchmode, coordinate, nodename, nodenumber, famnumber) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        switchmode: enum med_switch_mode const
        coordinate: med_float *const
        nodename: char *const
        nodenumber: med_int *const
        famnumber: med_int *const

    """
  return _medmesh.MEDmeshNodeRd(*args, **kwargs)

def MEDmeshElementWr(*args, **kwargs):
  """
    MEDmeshElementWr(fid, meshname, numdt, numit, dt, entitype, geotype, cmode, switchmode, nentity, connectivity, 
        withelementname, elementname, withelementnumber, elementnumber, 
        withfamnumber, famnumber) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        dt: med_float const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        switchmode: enum med_switch_mode const
        nentity: med_int const
        connectivity: med_int const *const
        withelementname: enum med_bool const
        elementname: char const *const
        withelementnumber: enum med_bool const
        elementnumber: med_int const *const
        withfamnumber: enum med_bool const
        famnumber: med_int const *const

    """
  return _medmesh.MEDmeshElementWr(*args, **kwargs)

def MEDmeshElementRd(*args, **kwargs):
  """
    MEDmeshElementRd(fid, meshname, numdt, numit, entitype, geotype, cmode, switchmode, connectivity, 
        elementname, elementnumber, famnumber) -> med_err

    Parameters:
        fid: med_idt const
        meshname: char const *const
        numdt: med_int const
        numit: med_int const
        entitype: enum med_entity_type const
        geotype: med_geometry_type const
        cmode: enum med_connectivity_mode const
        switchmode: enum med_switch_mode const
        connectivity: med_int *const
        elementname: char *const
        elementnumber: med_int *const
        famnumber: med_int *const

    """
  return _medmesh.MEDmeshElementRd(*args, **kwargs)
# This file is compatible with both classic and new-style classes.


